if exists (select 1 from sysobjects 
		where name = 'fn_GetPolicyForNonERPAriesCHF' and type = 'FN')
	drop function fn_GetPolicyForNonERPAriesCHF
GO
set ansi_nulls off
GO

SET QUOTED_IDENTIFIER ON
GO

---------------------------------------------------------------------
-----
----- Proc Name:  fn_GetPolicyForNonERPAriesCHF
-----
----- Version:  SQL Server 2012
-----
----- Created:  CSC
-----
----- Description: Retrieves DEP Master policy
-----
----- Modified: 
-----
---------------------------------------------------------------------
---------------------------------------------------------------------
CREATE function [dbo].[fn_GetPolicyForNonERPAriesCHF]
   (
 @ADJNO int, 
 @PERDID int,
 @PGMID int,
 @TYPID int,
 @IO varchar(2)
 )
returns VARCHAR(25)

as
begin
 DECLARE @POLICYNUMBER VARCHAR(25),
   @PGM_LKUP_TXT VARCHAR(20)
 
 SET @POLICYNUMBER = NULL 

 SELECT 
 @PGM_LKUP_TXT = LK.LKUP_TXT
 FROM DBO.PREM_ADJ_PGM PGM
 INNER JOIN DBO.LKUP LK ON (PGM.PGM_TYP_ID = LK.LKUP_ID)
 WHERE 
 PREM_ADJ_PGM_ID = @PGMID
 AND PGM.ACTV_IND = 1
 AND LK.ACTV_IND = 1 

 IF(SUBSTRING(@PGM_LKUP_TXT,1,3) = 'DEP' AND @IO='R')
 BEGIN

 SELECT TOP 1 @POLICYNUMBER =CASE WHEN LEN(COML_AGMT.POL_SYM_TXT)=3 THEN COML_AGMT.POL_SYM_TXT ELSE RTRIM(COML_AGMT.POL_SYM_TXT) END+ 
 RTRIM(COML_AGMT.POL_NBR_TXT) + COML_AGMT.POL_MODULUS_TXT
 FROM COML_AGMT 
 INNER JOIN PREM_ADJ_PARMET_DTL ON  PREM_ADJ_PARMET_DTL.COML_AGMT_ID=COML_AGMT.COML_AGMT_ID
 INNER JOIN PREM_ADJ_PARMET_SETUP ON PREM_ADJ_PARMET_SETUP.PREM_ADJ_PARMET_SETUP_ID=PREM_ADJ_PARMET_DTL.PREM_ADJ_PARMET_SETUP_ID 
 WHERE PREM_ADJ_PARMET_SETUP.PREM_ADJ_ID =  @ADJNO 
 AND PREM_ADJ_PARMET_SETUP.PREM_ADJ_PERD_ID = @PERDID 
 AND COML_AGMT.ACTV_IND = 1
 AND PREM_ADJ_PARMET_SETUP.ADJ_PARMET_TYP_ID=@TYPID
 AND SUBSTRING(COML_AGMT.POL_SYM_TXT,1,3) = 'DEP' 
 AND COML_AGMT.ADJ_TYP_ID NOT IN (62,69,448)
 
 END

 IF(@POLICYNUMBER IS NULL AND SUBSTRING(@PGM_LKUP_TXT,1,3) = 'DEP' AND @IO='D')
 BEGIN

 SELECT TOP 1 @POLICYNUMBER =CASE WHEN LEN(COML_AGMT.POL_SYM_TXT)=3 THEN COML_AGMT.POL_SYM_TXT ELSE RTRIM(COML_AGMT.POL_SYM_TXT) END+ 
 RTRIM(COML_AGMT.POL_NBR_TXT) + COML_AGMT.POL_MODULUS_TXT
 FROM COML_AGMT 
 INNER JOIN PREM_ADJ_PARMET_DTL ON  PREM_ADJ_PARMET_DTL.COML_AGMT_ID=COML_AGMT.COML_AGMT_ID
 INNER JOIN PREM_ADJ_PARMET_SETUP ON PREM_ADJ_PARMET_SETUP.PREM_ADJ_PARMET_SETUP_ID=PREM_ADJ_PARMET_DTL.PREM_ADJ_PARMET_SETUP_ID 
 WHERE PREM_ADJ_PARMET_SETUP.PREM_ADJ_ID =  @ADJNO 
 AND PREM_ADJ_PARMET_SETUP.PREM_ADJ_PERD_ID = @PERDID 
 AND COML_AGMT.ACTV_IND = 1
 AND PREM_ADJ_PARMET_SETUP.ADJ_PARMET_TYP_ID=@TYPID
 AND SUBSTRING(COML_AGMT.POL_SYM_TXT,1,3) = 'DEP' 
 AND COML_AGMT.ADJ_TYP_ID IN (62,69,448)

 END

 IF(@POLICYNUMBER IS NULL AND @IO='R')
 BEGIN

 SELECT TOP 1 @POLICYNUMBER =CASE WHEN LEN(COML_AGMT.POL_SYM_TXT)=3 THEN COML_AGMT.POL_SYM_TXT ELSE RTRIM(COML_AGMT.POL_SYM_TXT) END+ 
 RTRIM(COML_AGMT.POL_NBR_TXT) + COML_AGMT.POL_MODULUS_TXT
 FROM COML_AGMT 
 INNER JOIN PREM_ADJ_PARMET_DTL ON  PREM_ADJ_PARMET_DTL.COML_AGMT_ID=COML_AGMT.COML_AGMT_ID
 INNER JOIN PREM_ADJ_PARMET_SETUP ON PREM_ADJ_PARMET_SETUP.PREM_ADJ_PARMET_SETUP_ID=PREM_ADJ_PARMET_DTL.PREM_ADJ_PARMET_SETUP_ID 
 WHERE PREM_ADJ_PARMET_SETUP.PREM_ADJ_ID =  @ADJNO 
 AND PREM_ADJ_PARMET_SETUP.PREM_ADJ_PERD_ID = @PERDID AND COML_AGMT.ACTV_IND = 1
 AND PREM_ADJ_PARMET_SETUP.ADJ_PARMET_TYP_ID=@TYPID
 AND COML_AGMT.ADJ_TYP_ID NOT IN (62,69,448)
 ORDER BY COML_AGMT.POL_SYM_TXT DESC

 END

 
 IF(@POLICYNUMBER IS NULL AND @IO='D')
 BEGIN

 SELECT TOP 1 @POLICYNUMBER =CASE WHEN LEN(COML_AGMT.POL_SYM_TXT)=3 THEN COML_AGMT.POL_SYM_TXT ELSE RTRIM(COML_AGMT.POL_SYM_TXT) END+ 
 RTRIM(COML_AGMT.POL_NBR_TXT) + COML_AGMT.POL_MODULUS_TXT
 FROM COML_AGMT 
 INNER JOIN PREM_ADJ_PARMET_DTL ON  PREM_ADJ_PARMET_DTL.COML_AGMT_ID=COML_AGMT.COML_AGMT_ID
 INNER JOIN PREM_ADJ_PARMET_SETUP ON PREM_ADJ_PARMET_SETUP.PREM_ADJ_PARMET_SETUP_ID=PREM_ADJ_PARMET_DTL.PREM_ADJ_PARMET_SETUP_ID 
 WHERE PREM_ADJ_PARMET_SETUP.PREM_ADJ_ID =  @ADJNO 
 AND PREM_ADJ_PARMET_SETUP.PREM_ADJ_PERD_ID = @PERDID AND COML_AGMT.ACTV_IND = 1
 AND PREM_ADJ_PARMET_SETUP.ADJ_PARMET_TYP_ID=@TYPID
 AND COML_AGMT.ADJ_TYP_ID IN (62,69,448)
 ORDER BY COML_AGMT.POL_SYM_TXT DESC

 END
 
 IF(@POLICYNUMBER IS NULL)
 BEGIN
 SET @POLICYNUMBER=''
 END

 RETURN @POLICYNUMBER
end

GO
if object_id('fn_GetPolicyForNonERPAriesCHF') is not null
	print 'Created function fn_GetPolicyForNonERPAriesCHF'
else
	print 'Failed function fn_GetPolicyForNonERPAriesCHF'
go

if object_id('fn_GetPolicyForNonERPAriesCHF') is not null
	grant exec on fn_GetPolicyForNonERPAriesCHF to public
go 

