
truncate table INT_ORG
go

DBCC CHECKIDENT('INT_ORG', RESEED, 1)

go


INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('N','N','A',NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','Philadelphia','10',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','Pittsburgh','15',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC',NULL,NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','Atlanta','28',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','Dallas','36',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','New York','50',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','Glendale','51',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','Schaumburg','52',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','Chicago','53',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','Manhattan (NY, 1)','54',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','Syracuse','67',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','Boston','90',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Middle Market','MM',NULL,NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Specialties','SP','Atlanta','09',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Energy','GE','New York','50',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Energy','GE',NULL,NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Energy','GE','Houston','13',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Specialties','SP','Chicago','52',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Specialties','SP','New York','50',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Specialties','SP',NULL,NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','CC','San Francisco','81',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('XXX','SM',NULL,NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Surety Bond','SB',NULL,NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','Philadelphia','10',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','Pittsburgh','15',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','Atlanta','28',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','Dallas','36',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','Glendale','51',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','Schaumburg','52',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','Chicago','53',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','Manhattan (NY, 1)','54',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','Syracuse','67',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US',NULL,NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','San Francisco','81',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('USU','US','Boston','90',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Atlanta','28',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Dallas','36',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','San Francisco','81',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Minneapolis','34',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Home Office','HO',NULL,NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD',NULL,NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Hunt Valley','04',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Charlotte','08',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Philadelphia','10',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Chicago','30',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Pittsburgh','35',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','St. Louis','40',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Indianapolis','47',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Boston','90',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Denver','K8',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Detroit','ZF',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Houston','XC',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Jackson','ZI',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Kansas City','KE',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Los Angeles','KG',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Milwaukee','KJ',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Nashville','NA',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Orlando','ZO',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Phoenix','Z7',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Sacremento','4J',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Seattle','KV',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Construction','CD','Syracuse','67',NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO',NULL,NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO','Pittsburgh',NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO','Atlanta',NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO','Dallas',NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO','Glendale',NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO','Schaumburg',NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO','Chicago',NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO','Manhattan (NY, 1)',NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO','Syracuse',NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO','San Francisco',NULL,NULL,NULL,1,'01/01/2009')
INSERT INTO [INT_ORG] ([full_name],[bsn_unt_cd],[city_nm],[ofc_cd],[updt_user_id],[updt_dt],[crte_user_id],[crte_dt])VALUES('Global Corporate','PO','Syracuse',NULL,NULL,NULL,1,'01/01/2009')

go