
IF EXISTS (SELECT 1 FROM sysobjects 
	WHERE NAME = 'GetCalcInfoLegend' and TYPE = 'P')
	DROP PROC GetCalcInfoLegend
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO


---------------------------------------------------------------------
-----
-----	PROC NAME:	GetCalcInfoLegend
-----
-----	VERSION:	SQL SERVER 2005
-----
-----	AUTHOR :	SUNEEL KUMAR MOGALI
-----
-----	DESCRIPTION: RETURNS DATA WITH RESPECT TO THE GIVEN INVOICE NUMBER.
-----			
-----	ON EXIT:	
-----			
-----
-----	MODIFIED:	
-----			
----- 
---------------------------------------------------------------------

CREATE PROCEDURE [dbo].[GetCalcInfoLegend]
@ADJNO INT,
@FLAG INT,
@HISTFLAG BIT
AS
BEGIN

-- SET NOCOUNT ON added to prevent extra result sets from interfering with SELECT statements.
SET NOCOUNT ON;


BEGIN TRY


--To Create the temp tables
--WC ADJ CURRENT
		SELECT	PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM_ADJ_PGM_ID",
				PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PERD_ID",
				@ADJNO "PREM_ADJ_ID",				
				SUM(ARMIS_LOS_POL.PAID_IDNMTY_AMT) "WCADJCURRPAIDLOSS",
				SUM(ARMIS_LOS_POL.PAID_EXPS_AMT) "WCADJCURRPAIDALAE",
				SUM(ARMIS_LOS_POL.RESRV_IDNMTY_AMT) "WCADJCURRRESERLOSS",
				SUM(ARMIS_LOS_POL.RESRV_EXPS_AMT) "WCADJCURRRESERALAE",
				SUM(isnull(ARMIS_LOS_POL.EXC_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_PAID_EXPS_AMT,0) +
				    isnull(ARMIS_LOS_POL.NON_BILABL_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_PAID_EXPS_AMT,0) ) 
				"WCADJCURRPAIDEXCESS",
				SUM(isnull(ARMIS_LOS_POL.EXC_RESRVD_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_RESRV_EXPS_AMT, 0)  +
					isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_EXPS_AMT,0))
				"WCADJCURRRESEREXCESS",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_IDNMTY_AMT) "WCADJCURRPAIDWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_EXPS_AMT) "WCADJCURRPAIDALAEWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_IDNMTY_AMT) "WCADJCURRRESERVELOSSWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_EXPS_AMT) "WCADJCURRRESERVEALAEWITHIN"
		INTO #t_CalcInfoWCAdjCurrent
		FROM PREM_ADJ_PERD 
		INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID AND PREM_ADJ_PGM.ACTV_IND = 1 
		INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND COML_AGMT.CUSTMR_ID = PREM_ADJ_PGM.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1		
		INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
		AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND
		ARMIS_LOS_POL.CUSTMR_ID =  PREM_ADJ_PGM.CUSTMR_ID AND ARMIS_LOS_POL.PREM_ADJ_ID =
		PREM_ADJ_PERD.PREM_ADJ_ID AND ARMIS_LOS_POL.ACTV_IND = 1
		INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
		WHERE PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO AND COML_AGMT.COVG_TYP_ID IN (85,92)		 
		AND COML_AGMT.ADJ_TYP_ID IN (66,67,72,73)
		GROUP BY PREM_ADJ_PERD.PREM_ADJ_PERD_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		ORDER BY PREM_ADJ_PGM.PREM_ADJ_PGM_ID 


---- WC ADJ PRIOR
		SELECT	PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM_ADJ_PGM_ID",
				PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PERD_ID",
				@ADJNO "PREM_ADJ_ID",		
				SUM(ARMIS_LOS_POL.PAID_IDNMTY_AMT) "WCADJPRIORPAIDLOSS",
				SUM(ARMIS_LOS_POL.PAID_EXPS_AMT) "WCADJPRIORPAIDALAE",
				SUM(ARMIS_LOS_POL.RESRV_IDNMTY_AMT) "WCADJPRIORRESERLOSS",
				SUM(ARMIS_LOS_POL.RESRV_EXPS_AMT) "WCADJPRIORRESERALAE",
				SUM(isnull(ARMIS_LOS_POL.EXC_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_PAID_EXPS_AMT,0) +
				    isnull(ARMIS_LOS_POL.NON_BILABL_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_PAID_EXPS_AMT,0) ) 
				"WCADJPRIORPAIDEXCESS",
				SUM(isnull(ARMIS_LOS_POL.EXC_RESRVD_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_RESRV_EXPS_AMT, 0)  +
					isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_EXPS_AMT,0))
				"WCADJPRIORRESEREXCESS",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_IDNMTY_AMT) "WCADJPRIORPAIDWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_EXPS_AMT) "WCADJPRIORPAIDALAEWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_IDNMTY_AMT) "WCADJPRIORRESERVELOSSWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_EXPS_AMT) "WCADJPRIORRESERVEALAEWITHIN"
		INTO #t_CalcInfoWCAdjPrior
		FROM PREM_ADJ_PERD 
		INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID AND PREM_ADJ_PGM.ACTV_IND = 1 
		INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND COML_AGMT.CUSTMR_ID = PREM_ADJ_PGM.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1	
		INNER JOIN PREM_ADJ_STS ON PREM_ADJ_STS.PREM_ADJ_ID IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 ) 
		AND PREM_ADJ_STS.PREM_ADJ_STS_ID IN (SELECT MAX(PREM_ADJ_STS.PREM_ADJ_STS_ID) from PREM_ADJ_STS WHERE
		PREM_ADJ_STS.ADJ_STS_TYP_ID in (349,352) AND PREM_ADJ_STS.EXPI_DT IS NULL AND PREM_ADJ_STS.PREM_ADJ_ID IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 ))
		INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
		AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND
		ARMIS_LOS_POL.CUSTMR_ID =  PREM_ADJ_PGM.CUSTMR_ID AND ARMIS_LOS_POL.PREM_ADJ_ID =
		PREM_ADJ_PERD.PREM_ADJ_ID AND ARMIS_LOS_POL.ACTV_IND = 1
		INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
		WHERE PREM_ADJ_PERD.PREM_ADJ_ID 
						IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 
							) 
		AND COML_AGMT.COVG_TYP_ID IN (85,92)		 
		AND COML_AGMT.ADJ_TYP_ID IN (66,67,72,73)		
		GROUP BY PREM_ADJ_PERD.PREM_ADJ_PERD_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		ORDER BY PREM_ADJ_PGM.PREM_ADJ_PGM_ID 

	
---- WC CURRENT
		SELECT	PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM_ADJ_PGM_ID",
				PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PERD_ID",
				@ADJNO "PREM_ADJ_ID",				
				SUM(ARMIS_LOS_POL.PAID_IDNMTY_AMT) "WCCURRPAIDLOSS",
				SUM(ARMIS_LOS_POL.PAID_EXPS_AMT) "WCCURRPAIDALAE",
				SUM(ARMIS_LOS_POL.RESRV_IDNMTY_AMT) "WCCURRRESERLOSS",
				SUM(ARMIS_LOS_POL.RESRV_EXPS_AMT) "WCCURRRESERALAE",
				SUM(isnull(ARMIS_LOS_POL.EXC_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_PAID_EXPS_AMT,0) +
				    isnull(ARMIS_LOS_POL.NON_BILABL_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_PAID_EXPS_AMT,0) ) 
				"WCCURRPAIDEXCESS",
				SUM(isnull(ARMIS_LOS_POL.EXC_RESRVD_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_RESRV_EXPS_AMT, 0)  +
					isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_EXPS_AMT,0))
				"WCCURRRESEREXCESS",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_IDNMTY_AMT) "WCCURRPAIDWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_EXPS_AMT) "WCCURRPAIDALAEWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_IDNMTY_AMT) "WCCURRRESERVELOSSWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_EXPS_AMT) "WCCURRRESERVEALAEWITHIN"
		INTO #t_CalcInfoWCCurrent
		FROM PREM_ADJ_PERD 
		INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID AND PREM_ADJ_PGM.ACTV_IND = 1 
		INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND COML_AGMT.CUSTMR_ID = PREM_ADJ_PGM.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1	
		INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
		AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND
		ARMIS_LOS_POL.CUSTMR_ID =  PREM_ADJ_PGM.CUSTMR_ID AND ARMIS_LOS_POL.PREM_ADJ_ID =
		PREM_ADJ_PERD.PREM_ADJ_ID AND ARMIS_LOS_POL.ACTV_IND = 1
		INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
		WHERE PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO AND COML_AGMT.COVG_TYP_ID IN (85,92)		 
		AND COML_AGMT.ADJ_TYP_ID IN (63,65,70,71)
		GROUP BY PREM_ADJ_PERD.PREM_ADJ_PERD_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		ORDER BY PREM_ADJ_PGM.PREM_ADJ_PGM_ID 


---- WC PRIOR
		SELECT	PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM_ADJ_PGM_ID",
				PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PERD_ID",
				@ADJNO "PREM_ADJ_ID",
				SUM(ARMIS_LOS_POL.PAID_IDNMTY_AMT) "WCPRIORPAIDLOSS",
				SUM(ARMIS_LOS_POL.PAID_EXPS_AMT) "WCPRIORPAIDALAE",
				SUM(ARMIS_LOS_POL.RESRV_IDNMTY_AMT) "WCPRIORRESERLOSS",
				SUM(ARMIS_LOS_POL.RESRV_EXPS_AMT) "WCPRIORRESERALAE",
				SUM(isnull(ARMIS_LOS_POL.EXC_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_PAID_EXPS_AMT,0) +
					isnull(ARMIS_LOS_POL.NON_BILABL_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_PAID_EXPS_AMT,0) ) 
				"WCPRIORPAIDEXCESS",	
				SUM(isnull(ARMIS_LOS_POL.EXC_RESRVD_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_RESRV_EXPS_AMT, 0) +
					isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_EXPS_AMT,0))
				 "WCPRIORRESEREXCESS",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_IDNMTY_AMT) "WCPRIORPAIDWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_EXPS_AMT) "WCPRIORPAIDALAEWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_IDNMTY_AMT) "WCPRIORRESERVELOSSWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_EXPS_AMT) "WCPRIORRESERVEALAEWITHIN"
		INTO #t_CalcInfoWCPrior
		FROM PREM_ADJ_PERD 
		INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID AND PREM_ADJ_PGM.ACTV_IND = 1 
		INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND COML_AGMT.CUSTMR_ID = PREM_ADJ_PGM.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1	
		INNER JOIN PREM_ADJ_STS ON PREM_ADJ_STS.PREM_ADJ_ID IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 ) 
		AND PREM_ADJ_STS.PREM_ADJ_STS_ID IN (SELECT MAX(PREM_ADJ_STS.PREM_ADJ_STS_ID) from PREM_ADJ_STS WHERE
		PREM_ADJ_STS.ADJ_STS_TYP_ID in (349,352) AND PREM_ADJ_STS.EXPI_DT IS NULL AND PREM_ADJ_STS.PREM_ADJ_ID IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 ))
		INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
		AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND
		ARMIS_LOS_POL.CUSTMR_ID =  PREM_ADJ_PGM.CUSTMR_ID AND ARMIS_LOS_POL.PREM_ADJ_ID =
		PREM_ADJ_PERD.PREM_ADJ_ID AND ARMIS_LOS_POL.ACTV_IND = 1
		INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
		WHERE PREM_ADJ_PERD.PREM_ADJ_ID 
						IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 
							) 
		AND COML_AGMT.COVG_TYP_ID IN (85,92)		 
		AND COML_AGMT.ADJ_TYP_ID IN (63,65,70,71)
		GROUP BY PREM_ADJ_PERD.PREM_ADJ_PERD_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		ORDER BY PREM_ADJ_PGM.PREM_ADJ_PGM_ID 

---- GL CURRENT
		SELECT	PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM_ADJ_PGM_ID",
				PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PERD_ID",
				@ADJNO "PREM_ADJ_ID",	
				SUM(ARMIS_LOS_POL.PAID_IDNMTY_AMT) "GLCURRPAIDLOSS",
				SUM(ARMIS_LOS_POL.PAID_EXPS_AMT) "GLCURRPAIDALAE",
				SUM(ARMIS_LOS_POL.RESRV_IDNMTY_AMT) "GLCURRRESERLOSS",
				SUM(ARMIS_LOS_POL.RESRV_EXPS_AMT) "GLCURRRESERALAE",
				SUM(isnull(ARMIS_LOS_POL.EXC_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_PAID_EXPS_AMT,0) +
				    isnull(ARMIS_LOS_POL.NON_BILABL_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_PAID_EXPS_AMT,0) ) 
				 "GLCURRPAIDEXCESS",
				SUM(isnull(ARMIS_LOS_POL.EXC_RESRVD_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_RESRV_EXPS_AMT, 0)  +
					isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_EXPS_AMT,0))
				"GLCURRRESEREXCESS",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_IDNMTY_AMT) "GLCURRPAIDWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_EXPS_AMT) "GLCURRPAIDALAEWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_IDNMTY_AMT) "GLCURRRESERVELOSSWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_EXPS_AMT) "GLCURRRESERVEALAEWITHIN"
		INTO #t_CalcInfoGLCurrent
		FROM PREM_ADJ_PERD 
		INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID AND PREM_ADJ_PGM.ACTV_IND = 1 
		INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND COML_AGMT.CUSTMR_ID = PREM_ADJ_PGM.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1	
		INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
		AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND
		ARMIS_LOS_POL.CUSTMR_ID =  PREM_ADJ_PGM.CUSTMR_ID AND ARMIS_LOS_POL.PREM_ADJ_ID =
		PREM_ADJ_PERD.PREM_ADJ_ID AND ARMIS_LOS_POL.ACTV_IND = 1
		INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
		WHERE PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO AND COML_AGMT.COVG_TYP_ID IN (88,89,90,91)		 
		AND COML_AGMT.ADJ_TYP_ID IN (63,65,70,71)
		GROUP BY PREM_ADJ_PERD.PREM_ADJ_PERD_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		ORDER BY PREM_ADJ_PGM.PREM_ADJ_PGM_ID 


---- GL PRIOR
		SELECT	PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM_ADJ_PGM_ID",
				PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PERD_ID",
				@ADJNO "PREM_ADJ_ID",
				SUM(ARMIS_LOS_POL.PAID_IDNMTY_AMT) "GLPRIORPAIDLOSS",
				SUM(ARMIS_LOS_POL.PAID_EXPS_AMT) "GLPRIORPAIDALAE",
				SUM(ARMIS_LOS_POL.RESRV_IDNMTY_AMT) "GLPRIORRESERLOSS",
				SUM(ARMIS_LOS_POL.RESRV_EXPS_AMT) "GLPRIORRESERALAE",
				SUM(isnull(ARMIS_LOS_POL.EXC_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_PAID_EXPS_AMT,0) +
				    isnull(ARMIS_LOS_POL.NON_BILABL_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_PAID_EXPS_AMT,0) ) 
				"GLPRIORPAIDEXCESS",
				SUM(isnull(ARMIS_LOS_POL.EXC_RESRVD_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_RESRV_EXPS_AMT, 0)  +
					isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_EXPS_AMT,0))
				"GLPRIORRESEREXCESS",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_IDNMTY_AMT) "GLPRIORPAIDWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_EXPS_AMT) "GLPRIORPAIDALAEWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_IDNMTY_AMT) "GLPRIORRESERVELOSSWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_EXPS_AMT) "GLPRIORRESERVEALAEWITHIN"
		INTO #t_CalcInfoGLPrior
		FROM PREM_ADJ_PERD 
		INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID AND PREM_ADJ_PGM.ACTV_IND = 1 
		INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND COML_AGMT.CUSTMR_ID = PREM_ADJ_PGM.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1	
		INNER JOIN PREM_ADJ_STS ON PREM_ADJ_STS.PREM_ADJ_ID IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 ) 
		AND PREM_ADJ_STS.PREM_ADJ_STS_ID IN (SELECT MAX(PREM_ADJ_STS.PREM_ADJ_STS_ID) from PREM_ADJ_STS WHERE
		PREM_ADJ_STS.ADJ_STS_TYP_ID in (349,352) AND PREM_ADJ_STS.EXPI_DT IS NULL AND PREM_ADJ_STS.PREM_ADJ_ID IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 ))
		INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
		AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND
		ARMIS_LOS_POL.CUSTMR_ID =  PREM_ADJ_PGM.CUSTMR_ID AND ARMIS_LOS_POL.PREM_ADJ_ID =
		PREM_ADJ_PERD.PREM_ADJ_ID AND ARMIS_LOS_POL.ACTV_IND = 1
		INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
		WHERE PREM_ADJ_PERD.PREM_ADJ_ID 
						IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 
							) 
		AND COML_AGMT.COVG_TYP_ID IN (88,89,90,91)		 
		AND COML_AGMT.ADJ_TYP_ID IN (63,65,70,71)
		GROUP BY PREM_ADJ_PERD.PREM_ADJ_PERD_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		ORDER BY PREM_ADJ_PGM.PREM_ADJ_PGM_ID 

---- AL CURRENT
		SELECT	PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM_ADJ_PGM_ID",
				PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PERD_ID",
				@ADJNO "PREM_ADJ_ID",
				SUM(ARMIS_LOS_POL.PAID_IDNMTY_AMT) "ALCURRPAIDLOSS",
				SUM(ARMIS_LOS_POL.PAID_EXPS_AMT) "ALCURRPAIDALAE",
				SUM(ARMIS_LOS_POL.RESRV_IDNMTY_AMT) "ALCURRRESERLOSS",
				SUM(ARMIS_LOS_POL.RESRV_EXPS_AMT) "ALCURRRESERALAE",
				SUM(isnull(ARMIS_LOS_POL.EXC_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_PAID_EXPS_AMT,0) +
				    isnull(ARMIS_LOS_POL.NON_BILABL_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_PAID_EXPS_AMT,0) ) 
				"ALCURRPAIDEXCESS",
				SUM(isnull(ARMIS_LOS_POL.EXC_RESRVD_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_RESRV_EXPS_AMT, 0)  +
					isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_EXPS_AMT,0))
				"ALCURRRESEREXCESS",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_IDNMTY_AMT) "ALCURRPAIDWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_EXPS_AMT) "ALCURRPAIDALAEWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_IDNMTY_AMT) "ALCURRRESERVELOSSWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_EXPS_AMT) "ALCURRRESERVEALAEWITHIN"
		INTO #t_CalcInfoALCurrent
		FROM PREM_ADJ_PERD 
		INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID AND PREM_ADJ_PGM.ACTV_IND = 1 
		INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND COML_AGMT.CUSTMR_ID = PREM_ADJ_PGM.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1	
		INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
		AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND
		ARMIS_LOS_POL.CUSTMR_ID =  PREM_ADJ_PGM.CUSTMR_ID AND ARMIS_LOS_POL.PREM_ADJ_ID =
		PREM_ADJ_PERD.PREM_ADJ_ID AND ARMIS_LOS_POL.ACTV_IND = 1	
		INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
		WHERE PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO AND COML_AGMT.COVG_TYP_ID IN (86,87)		 
		AND COML_AGMT.ADJ_TYP_ID IN (63,65,70,71)
		GROUP BY PREM_ADJ_PERD.PREM_ADJ_PERD_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		ORDER BY PREM_ADJ_PGM.PREM_ADJ_PGM_ID 

---- AL PRIOR
		SELECT	PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM_ADJ_PGM_ID",
				PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PERD_ID",
				@ADJNO "PREM_ADJ_ID",
				SUM(ARMIS_LOS_POL.PAID_IDNMTY_AMT) "ALPRIORPAIDLOSS",
				SUM(ARMIS_LOS_POL.PAID_EXPS_AMT) "ALPRIORPAIDALAE",
				SUM(ARMIS_LOS_POL.RESRV_IDNMTY_AMT) "ALPRIORRESERLOSS",
				SUM(ARMIS_LOS_POL.RESRV_EXPS_AMT) "ALPRIORRESERALAE",
				SUM(isnull(ARMIS_LOS_POL.EXC_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_PAID_EXPS_AMT,0) +
				    isnull(ARMIS_LOS_POL.NON_BILABL_PAID_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_PAID_EXPS_AMT,0) ) 
				"ALPRIORPAIDEXCESS",
				SUM(isnull(ARMIS_LOS_POL.EXC_RESRVD_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.EXC_RESRV_EXPS_AMT, 0)  +
					isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_IDNMTY_AMT,0) + isnull(ARMIS_LOS_POL.NON_BILABL_RESRV_EXPS_AMT,0))
				"ALPRIORRESEREXCESS",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_IDNMTY_AMT) "ALPRIORPAIDWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_PAID_EXPS_AMT) "ALPRIORPAIDALAEWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_IDNMTY_AMT) "ALPRIORRESERVELOSSWITHIN",
				SUM(ARMIS_LOS_POL.SUBJ_RESRV_EXPS_AMT) "ALPRIORRESERVEALAEWITHIN"
		INTO #t_CalcInfoALPrior
		FROM PREM_ADJ_PERD 
		INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID AND PREM_ADJ_PGM.ACTV_IND = 1 
		INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND COML_AGMT.CUSTMR_ID = PREM_ADJ_PGM.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1	
		INNER JOIN PREM_ADJ_STS ON PREM_ADJ_STS.PREM_ADJ_ID IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 ) 
		AND PREM_ADJ_STS.PREM_ADJ_STS_ID IN (SELECT MAX(PREM_ADJ_STS.PREM_ADJ_STS_ID) from PREM_ADJ_STS WHERE
		PREM_ADJ_STS.ADJ_STS_TYP_ID in (349,352) AND PREM_ADJ_STS.EXPI_DT IS NULL AND PREM_ADJ_STS.PREM_ADJ_ID IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 ))
		INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
		AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND
		ARMIS_LOS_POL.CUSTMR_ID =  PREM_ADJ_PGM.CUSTMR_ID AND ARMIS_LOS_POL.PREM_ADJ_ID =
		PREM_ADJ_PERD.PREM_ADJ_ID AND ARMIS_LOS_POL.ACTV_IND = 1	
		INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
		WHERE PREM_ADJ_PERD.PREM_ADJ_ID 
						IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 
							) 
		AND COML_AGMT.COVG_TYP_ID IN (86,87)		 
		AND COML_AGMT.ADJ_TYP_ID IN (63,65,70,71)
		GROUP BY PREM_ADJ_PERD.PREM_ADJ_PERD_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		ORDER BY PREM_ADJ_PGM.PREM_ADJ_PGM_ID 



--#FinalCurrent

SELECT	PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM_ADJ_PGM_ID",
				PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PERD_ID",
				@ADJNO "PREM_ADJ_ID"			
		INTO #FinalCurrent
		FROM PREM_ADJ_PERD 
		INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID AND PREM_ADJ_PGM.ACTV_IND = 1 
		INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND COML_AGMT.CUSTMR_ID = PREM_ADJ_PGM.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1	
		INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
		AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND
		ARMIS_LOS_POL.CUSTMR_ID =  PREM_ADJ_PGM.CUSTMR_ID AND ARMIS_LOS_POL.PREM_ADJ_ID =
		PREM_ADJ_PERD.PREM_ADJ_ID AND ARMIS_LOS_POL.ACTV_IND = 1	
		INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
		WHERE PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO AND COML_AGMT.COVG_TYP_ID IN (85,86,87,88,89,90,91,92)		 
		AND COML_AGMT.ADJ_TYP_ID IN (63,65,70,71,66,67,72,73)
		GROUP BY PREM_ADJ_PERD.PREM_ADJ_PERD_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		ORDER BY PREM_ADJ_PGM.PREM_ADJ_PGM_ID 

--#FinalPrior

SELECT	PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM_ADJ_PGM_ID",
				PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PERD_ID",
				@ADJNO "PREM_ADJ_ID"			
		INTO #FinalPrior
		FROM PREM_ADJ_PERD 
		INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID AND PREM_ADJ_PGM.ACTV_IND = 1 
		INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND COML_AGMT.CUSTMR_ID = PREM_ADJ_PGM.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1	
		INNER JOIN PREM_ADJ_STS ON PREM_ADJ_STS.PREM_ADJ_ID IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 ) 
		AND PREM_ADJ_STS.PREM_ADJ_STS_ID IN (SELECT MAX(PREM_ADJ_STS.PREM_ADJ_STS_ID) from PREM_ADJ_STS WHERE
		PREM_ADJ_STS.ADJ_STS_TYP_ID in (349,352) AND PREM_ADJ_STS.EXPI_DT IS NULL AND PREM_ADJ_STS.PREM_ADJ_ID IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 ))
		INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
		AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND
		ARMIS_LOS_POL.CUSTMR_ID =  PREM_ADJ_PGM.CUSTMR_ID AND ARMIS_LOS_POL.PREM_ADJ_ID =
		PREM_ADJ_PERD.PREM_ADJ_ID AND ARMIS_LOS_POL.ACTV_IND = 1	
		INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
		WHERE PREM_ADJ_PERD.PREM_ADJ_ID 
						IN (SELECT prior_prem_adj_id FROM PREM_ADJ_PGM
							INNER JOIN PREM_ADJ_PERD ON 
							PREM_ADJ_PERD.PREM_ADJ_ID = @ADJNO
							AND PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PERD.PREM_ADJ_PGM_ID
							AND PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID 
							AND PREM_ADJ_PGM.ACTV_IND = 1 
							) 
		AND COML_AGMT.COVG_TYP_ID IN (85,86,87,88,89,90,91,92)		 
		AND COML_AGMT.ADJ_TYP_ID IN (63,65,70,71,66,67,72,73)
		GROUP BY PREM_ADJ_PERD.PREM_ADJ_PERD_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID
		ORDER BY PREM_ADJ_PGM.PREM_ADJ_PGM_ID 



SELECT	DISTINCT	#t_CalcInfoWCCurrent.PREM_ADJ_PGM_ID,
			#t_CalcInfoWCCurrent.PERD_ID,
			#t_CalcInfoWCCurrent.PREM_ADJ_ID,
			#t_CalcInfoWCCurrent.[WCCURRPAIDLOSS],
			#t_CalcInfoWCCurrent.[WCCURRPAIDALAE],
			#t_CalcInfoWCCurrent.[WCCURRRESERLOSS],
			#t_CalcInfoWCCurrent.[WCCURRRESERALAE],
			#t_CalcInfoWCCurrent.[WCCURRPAIDEXCESS],
			#t_CalcInfoWCCurrent.[WCCURRRESEREXCESS],
			#t_CalcInfoWCCurrent.[WCCURRPAIDWITHIN],
			#t_CalcInfoWCCurrent.[WCCURRPAIDALAEWITHIN],
			#t_CalcInfoWCCurrent.[WCCURRRESERVELOSSWITHIN],
			#t_CalcInfoWCCurrent.[WCCURRRESERVEALAEWITHIN],

			#t_CalcInfoWCPrior.PREM_ADJ_PGM_ID,
			#t_CalcInfoWCPrior.PERD_ID,
			#t_CalcInfoWCPrior.PREM_ADJ_ID,
			#t_CalcInfoWCPrior.[WCPRIORPAIDLOSS],
			#t_CalcInfoWCPrior.[WCPRIORPAIDALAE],
			#t_CalcInfoWCPrior.[WCPRIORRESERLOSS],
			#t_CalcInfoWCPrior.[WCPRIORRESERALAE],
			#t_CalcInfoWCPrior.[WCPRIORPAIDEXCESS],
			#t_CalcInfoWCPrior.[WCPRIORRESEREXCESS],
			#t_CalcInfoWCPrior.[WCPRIORPAIDWITHIN],
			#t_CalcInfoWCPrior.[WCPRIORPAIDALAEWITHIN],
			#t_CalcInfoWCPrior.[WCPRIORRESERVELOSSWITHIN],
			#t_CalcInfoWCPrior.[WCPRIORRESERVEALAEWITHIN],

ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDLOSS],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDLOSS],0) "WC Paid Loss Change",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDALAE],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDALAE],0) "WC Paid ALAE Change",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERLOSS],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERLOSS],0) "WC Reserv Loss Change",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERALAE],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERALAE],0) "WC Reserv ALAE Change",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDEXCESS],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDEXCESS],0) "WC Excess Paid Loss Change",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESEREXCESS],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESEREXCESS],0) "WC Excess Reserv Change",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDWITHIN],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDWITHIN],0) "WC Paid Loss Within Change",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDALAEWITHIN],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDALAEWITHIN],0) "WC Paid ALAE Within Change",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERVELOSSWITHIN],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERVELOSSWITHIN],0) "WC Reserv Loss Within Change",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERVEALAEWITHIN],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERVEALAEWITHIN],0) "WC Reserv ALAE Within Change",

#t_CalcInfoGLCurrent.PREM_ADJ_PGM_ID,
#t_CalcInfoGLCurrent.PERD_ID,
			#t_CalcInfoGLCurrent.PREM_ADJ_ID,
			#t_CalcInfoGLCurrent.[GLCURRPAIDLOSS],
			#t_CalcInfoGLCurrent.[GLCURRPAIDALAE],
			#t_CalcInfoGLCurrent.[GLCURRRESERLOSS],
			#t_CalcInfoGLCurrent.[GLCURRRESERALAE],
			#t_CalcInfoGLCurrent.[GLCURRPAIDEXCESS],
			#t_CalcInfoGLCurrent.[GLCURRRESEREXCESS],
			#t_CalcInfoGLCurrent.[GLCURRPAIDWITHIN],
			#t_CalcInfoGLCurrent.[GLCURRPAIDALAEWITHIN],
			#t_CalcInfoGLCurrent.[GLCURRRESERVELOSSWITHIN],
			#t_CalcInfoGLCurrent.[GLCURRRESERVEALAEWITHIN],

#t_CalcInfoGLPrior.PREM_ADJ_PGM_ID,
#t_CalcInfoGLPrior.PERD_ID,
			#t_CalcInfoGLPrior.PREM_ADJ_ID,			
			#t_CalcInfoGLPrior.[GLPRIORPAIDLOSS],
			#t_CalcInfoGLPrior.[GLPRIORPAIDALAE],
			#t_CalcInfoGLPrior.[GLPRIORRESERLOSS],
			#t_CalcInfoGLPrior.[GLPRIORRESERALAE],
			#t_CalcInfoGLPrior.[GLPRIORPAIDEXCESS],
			#t_CalcInfoGLPrior.[GLPRIORRESEREXCESS],
			#t_CalcInfoGLPrior.[GLPRIORPAIDWITHIN],
			#t_CalcInfoGLPrior.[GLPRIORPAIDALAEWITHIN],
			#t_CalcInfoGLPrior.[GLPRIORRESERVELOSSWITHIN],
			#t_CalcInfoGLPrior.[GLPRIORRESERVEALAEWITHIN],

ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDLOSS],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDLOSS],0) "GL Paid Loss Change",
ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDALAE],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDALAE],0) "GL Paid ALAE Change",
ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERLOSS],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERLOSS],0) "GL Reserv Loss Change",
ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERALAE],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERALAE],0) "GL Reserv ALAE Change",
ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDEXCESS],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDEXCESS],0) "GL Excess Paid Change",
ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESEREXCESS],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESEREXCESS],0) "GL Excess Reserv Change",
ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDWITHIN],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDWITHIN],0) "GL Paid Loss Within Change",
ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDALAEWITHIN],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDALAEWITHIN],0) "GL Paid ALAE Within Change",
ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERVELOSSWITHIN],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERVELOSSWITHIN],0) "GL Reserv Loss Within Change",
ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERVEALAEWITHIN],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERVEALAEWITHIN],0) "GL Reserv AlAE Within Change",

#t_CalcInfoALCurrent.PREM_ADJ_PGM_ID,
#t_CalcInfoALCurrent.PERD_ID,
			#t_CalcInfoALCurrent.PREM_ADJ_ID,
			#t_CalcInfoALCurrent.[ALCURRPAIDLOSS],
			#t_CalcInfoALCurrent.[ALCURRPAIDALAE],
			#t_CalcInfoALCurrent.[ALCURRRESERLOSS],
			#t_CalcInfoALCurrent.[ALCURRRESERALAE],
			#t_CalcInfoALCurrent.[ALCURRPAIDEXCESS],
			#t_CalcInfoALCurrent.[ALCURRRESEREXCESS],
			#t_CalcInfoALCurrent.[ALCURRPAIDWITHIN],
			#t_CalcInfoALCurrent.[ALCURRPAIDALAEWITHIN],
			#t_CalcInfoALCurrent.[ALCURRRESERVELOSSWITHIN],
			#t_CalcInfoALCurrent.[ALCURRRESERVEALAEWITHIN],

#t_CalcInfoALPrior.PREM_ADJ_PGM_ID,
#t_CalcInfoALPrior.PERD_ID,
			#t_CalcInfoALPrior.PREM_ADJ_ID,			
			#t_CalcInfoALPrior.[ALPRIORPAIDLOSS],
			#t_CalcInfoALPrior.[ALPRIORPAIDALAE],
			#t_CalcInfoALPrior.[ALPRIORRESERLOSS],
			#t_CalcInfoALPrior.[ALPRIORRESERALAE],
			#t_CalcInfoALPrior.[ALPRIORPAIDEXCESS],
			#t_CalcInfoALPrior.[ALPRIORRESEREXCESS],
			#t_CalcInfoALPrior.[ALPRIORPAIDWITHIN],
			#t_CalcInfoALPrior.[ALPRIORPAIDALAEWITHIN],
			#t_CalcInfoALPrior.[ALPRIORRESERVELOSSWITHIN],
			#t_CalcInfoALPrior.[ALPRIORRESERVEALAEWITHIN],

ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDLOSS],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDLOSS],0) "AL Paid Loss Change",
ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDALAE],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDALAE],0) "AL Paid ALAE Change",
ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERLOSS],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERLOSS],0) "AL Reserv Loss Change",
ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERALAE],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERALAE],0) "AL Reserv ALAE Change",
ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDEXCESS],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDEXCESS],0) "AL Excess Paid Change",
ISNULL(#t_CalcInfoALCurrent.[ALCURRRESEREXCESS],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORRESEREXCESS],0) "AL Excess Reserv Change",
ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDWITHIN],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDWITHIN],0) "AL Paid Loss Within Change",
ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDALAEWITHIN],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDALAEWITHIN],0) "AL Paid ALAE Within Change",
ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERVELOSSWITHIN],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERVELOSSWITHIN],0) "AL Reserv Loss Within Change",
ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERVEALAEWITHIN],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERVEALAEWITHIN],0) "AL Reserv ALAE Within Change",

#t_CalcInfoWCAdjCurrent.PREM_ADJ_PGM_ID,
#t_CalcInfoWCAdjCurrent.PERD_ID,
			#t_CalcInfoWCAdjCurrent.PREM_ADJ_ID,			
			#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDLOSS],
			#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDALAE],
			#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERLOSS],
			#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERALAE],
			#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDEXCESS],
			#t_CalcInfoWCAdjCurrent.[WCADJCURRRESEREXCESS],
			#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDWITHIN],
			#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDALAEWITHIN],
			#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERVELOSSWITHIN],
			#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERVEALAEWITHIN],

#t_CalcInfoWCAdjPrior.PREM_ADJ_PGM_ID,
#t_CalcInfoWCAdjPrior.PERD_ID,
			#t_CalcInfoWCAdjPrior.PREM_ADJ_ID,
			#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDLOSS],
			#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDALAE],
			#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERLOSS],
			#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERALAE],
			#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDEXCESS],
			#t_CalcInfoWCAdjPrior.[WCADJPRIORRESEREXCESS],
			#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDWITHIN],
			#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDALAEWITHIN],
			#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERVELOSSWITHIN],
			#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERVEALAEWITHIN],

ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDLOSS],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDLOSS],0) "WCAdj Paid Loss Change",
ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDALAE],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDALAE],0) "WCAdj Paid Alae Change",
ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERLOSS],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERLOSS],0) "WCAdj Reser Loss Change",
ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERALAE],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERALAE],0) "WCAdj Reser ALAE Change",
ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDEXCESS],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDEXCESS],0) "WCAdj Paid Excess Change",
ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESEREXCESS],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESEREXCESS],0) "WCAdj Reserv Excess Change",
ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDWITHIN],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDWITHIN],0) "WCAdj Paid Loss Within Change",
ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDALAEWITHIN],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDALAEWITHIN],0) "WCAdj Paid ALAE Within Change",
ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERVELOSSWITHIN],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERVELOSSWITHIN],0) "WCAdj Reserv Loss Within Change",
ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERVEALAEWITHIN],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERVEALAEWITHIN],0) "WCAdj Reserv ALAE Within Change",

ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDLOSS],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDLOSS],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDLOSS],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDLOSS],0) "Total Current Paid Loss",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDALAE],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDALAE],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDALAE],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDALAE],0) "Total Current Paid ALAE",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERLOSS],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERLOSS],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERLOSS],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERLOSS],0) "Total Current Reserv Loss",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERALAE],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERALAE],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERALAE],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERALAE],0) "Total Current Reserv ALAE",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDEXCESS],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDEXCESS],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDEXCESS],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDEXCESS],0) "Total Current Excess Paid",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESEREXCESS],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESEREXCESS],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRRESEREXCESS],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESEREXCESS],0) "Total Current Excess Reserv",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDWITHIN],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDWITHIN],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDWITHIN],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDWITHIN],0) "Total Current Paid Loss Within",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDALAEWITHIN],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDALAEWITHIN],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDALAEWITHIN],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDALAEWITHIN],0) "Total Current Paid ALAE Within",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERVELOSSWITHIN],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERVELOSSWITHIN],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERVELOSSWITHIN],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERVELOSSWITHIN],0) "Total Current Reserv Loss Within",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERVEALAEWITHIN],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERVEALAEWITHIN],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERVEALAEWITHIN],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERVEALAEWITHIN],0) "Total Current Reserv ALAE Within",

ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDLOSS],0)+ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDLOSS],0)+ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDLOSS],0)+ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDLOSS],0) "Total Prior Paid Loss",
ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDALAE],0)+ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDALAE],0)+ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDALAE],0)+ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDALAE],0) "Total Prior Paid ALAE",
ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERLOSS],0)+ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERLOSS],0)+ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERLOSS],0)+ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERLOSS],0) "Total Prior Reserv Loss",
ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERALAE],0)+ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERALAE],0)+ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERALAE],0)+ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERALAE],0) "Total Prior Reserv ALAE",
ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDEXCESS],0)+ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDEXCESS],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDEXCESS],0)+ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDEXCESS],0) "Total Prior Paid Excess",
ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESEREXCESS],0)+ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESEREXCESS],0)+ISNULL(#t_CalcInfoALPrior.[ALPRIORRESEREXCESS],0)+ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESEREXCESS],0) "Total Prior Reserv Excess",
ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDWITHIN],0)+ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDWITHIN],0)+ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDWITHIN],0)+ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDWITHIN],0) "Total Prior Paid Within",
ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDALAEWITHIN],0)+ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDALAEWITHIN],0)+ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDALAEWITHIN],0)+ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDALAEWITHIN],0) "Total Prior Paid ALAE Within",
ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERVELOSSWITHIN],0)+ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERVELOSSWITHIN],0)+ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERVELOSSWITHIN],0)+ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERVELOSSWITHIN],0) "Total Prior Reserv Loss Within",
ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERVEALAEWITHIN],0)+ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERVEALAEWITHIN],0)+ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERVEALAEWITHIN],0)+ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERVEALAEWITHIN],0) "Total Prior Reserv ALAE Within",

ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDLOSS],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDLOSS],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDLOSS],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDLOSS],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDLOSS],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDLOSS],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDLOSS],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDLOSS],0) "Total Change Paid Loss",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDALAE],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDALAE],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDALAE],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDALAE],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDALAE],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDALAE],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDALAE],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDALAE],0) "Total Change Paid ALAE",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERLOSS],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERLOSS],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERLOSS],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERLOSS],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERLOSS],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERLOSS],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERLOSS],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERLOSS],0) "Total Change Reserv Loss",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERALAE],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERALAE],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERALAE],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERALAE],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERALAE],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERALAE],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERALAE],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERALAE],0) "Total Change Reserv ALAE",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDEXCESS],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDEXCESS],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDEXCESS],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDEXCESS],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDEXCESS],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDEXCESS],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDEXCESS],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDEXCESS],0) "Total Change Paid Excess",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESEREXCESS],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESEREXCESS],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESEREXCESS],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESEREXCESS],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRRESEREXCESS],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORRESEREXCESS],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESEREXCESS],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESEREXCESS],0) "Total Change Reserv Excess",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDWITHIN],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDWITHIN],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDWITHIN],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDWITHIN],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDWITHIN],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDWITHIN],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDWITHIN],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDWITHIN],0) "Total Within Change Paid Loss",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRPAIDALAEWITHIN],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORPAIDALAEWITHIN],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRPAIDALAEWITHIN],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORPAIDALAEWITHIN],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRPAIDALAEWITHIN],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORPAIDALAEWITHIN],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRPAIDALAEWITHIN],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORPAIDALAEWITHIN],0) "Total Within Change Paid ALAE",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERVELOSSWITHIN],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERVELOSSWITHIN],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERVELOSSWITHIN],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERVELOSSWITHIN],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERVELOSSWITHIN],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERVELOSSWITHIN],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERVELOSSWITHIN],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERVELOSSWITHIN],0) "Total Within Change Reserv Loss",
ISNULL(#t_CalcInfoWCCurrent.[WCCURRRESERVEALAEWITHIN],0)-ISNULL(#t_CalcInfoWCPrior.[WCPRIORRESERVEALAEWITHIN],0)+ISNULL(#t_CalcInfoGLCurrent.[GLCURRRESERVEALAEWITHIN],0)-ISNULL(#t_CalcInfoGLPrior.[GLPRIORRESERVEALAEWITHIN],0)+ISNULL(#t_CalcInfoALCurrent.[ALCURRRESERVEALAEWITHIN],0)-ISNULL(#t_CalcInfoALPrior.[ALPRIORRESERVEALAEWITHIN],0)+ISNULL(#t_CalcInfoWCAdjCurrent.[WCADJCURRRESERVEALAEWITHIN],0)-ISNULL(#t_CalcInfoWCAdjPrior.[WCADJPRIORRESERVEALAEWITHIN],0) "Total Within Change Reserv ALAE",

#FinalCurrent.PREM_ADJ_PGM_ID,
#FinalCurrent.PERD_ID,
			#FinalCurrent.PREM_ADJ_ID

FROM  #FinalCurrent LEFT OUTER JOIN #t_CalcInfoWCCurrent ON #FinalCurrent.PREM_ADJ_PGM_ID = #t_CalcInfoWCCurrent.PREM_ADJ_PGM_ID
AND #FinalCurrent.PERD_ID = #t_CalcInfoWCCurrent.PERD_ID
LEFT OUTER JOIN #t_CalcInfoGLCurrent ON #FinalCurrent.PREM_ADJ_PGM_ID = #t_CalcInfoGLCurrent.PREM_ADJ_PGM_ID
AND #FinalCurrent.PERD_ID = #t_CalcInfoGLCurrent.PERD_ID
LEFT OUTER JOIN #t_CalcInfoALCurrent ON #FinalCurrent.PREM_ADJ_PGM_ID = #t_CalcInfoALCurrent.PREM_ADJ_PGM_ID
AND #FinalCurrent.PERD_ID = #t_CalcInfoALCurrent.PERD_ID
LEFT OUTER JOIN #t_CalcInfoWCAdjCurrent ON #FinalCurrent.PREM_ADJ_PGM_ID = #t_CalcInfoWCAdjCurrent.PREM_ADJ_PGM_ID
AND #FinalCurrent.PERD_ID = #t_CalcInfoWCAdjCurrent.PERD_ID
LEFT OUTER JOIN #FinalPrior ON #FinalPrior.PREM_ADJ_PGM_ID = #FinalCurrent.PREM_ADJ_PGM_ID
--AND #FinalPrior.PERD_ID = #FinalCurrent.PERD_ID
LEFT OUTER JOIN #t_CalcInfoWCPrior ON #FinalPrior.PREM_ADJ_PGM_ID = #t_CalcInfoWCPrior.PREM_ADJ_PGM_ID
AND #FinalPrior.PERD_ID = #t_CalcInfoWCPrior.PERD_ID
LEFT OUTER JOIN #t_CalcInfoGLPrior ON #FinalPrior.PREM_ADJ_PGM_ID = #t_CalcInfoGLPrior.PREM_ADJ_PGM_ID
AND #FinalPrior.PERD_ID = #t_CalcInfoGLPrior.PERD_ID
LEFT OUTER JOIN #t_CalcInfoALPrior ON #FinalPrior.PREM_ADJ_PGM_ID = #t_CalcInfoALPrior.PREM_ADJ_PGM_ID
AND #FinalPrior.PERD_ID = #t_CalcInfoALPrior.PERD_ID
LEFT OUTER JOIN #t_CalcInfoWCAdjPrior ON #FinalPrior.PREM_ADJ_PGM_ID = #t_CalcInfoWCAdjPrior.PREM_ADJ_PGM_ID
AND #FinalPrior.PERD_ID = #t_CalcInfoWCAdjPrior.PERD_ID

drop table #t_CalcInfoWCCurrent
drop table #t_CalcInfoWCPrior
drop table #t_CalcInfoGLCurrent
drop table #t_CalcInfoGLPrior
drop table #t_CalcInfoALCurrent
drop table #t_CalcInfoALPrior
drop table #t_CalcInfoWCAdjCurrent
drop table #t_CalcInfoWCAdjPrior
drop table #FinalPrior
drop table #FinalCurrent




END TRY
BEGIN CATCH

	SELECT 
    ERROR_NUMBER() AS ERRORNUMBER,
    ERROR_SEVERITY() AS ERRORSEVERITY,
    ERROR_STATE() AS ERRORSTATE,
    ERROR_PROCEDURE() AS ERRORPROCEDURE,
    ERROR_LINE() AS ERRORLINE,
    ERROR_MESSAGE() AS ERRORMESSAGE;


END CATCH
END

GO

IF OBJECT_ID('GetCalcInfoLegend') IS NOT NULL
	PRINT 'CREATED PROCEDURE GetCalcInfoLegend'
ELSE
	PRINT 'FAILED CREATING PROCEDURE GetCalcInfoLegend'
GO

IF OBJECT_ID('GetCalcInfoLegend') IS NOT NULL
	GRANT EXEC ON GetCalcInfoLegend TO PUBLIC
GO








