
if exists (select 1 from sysobjects 
		where name = 'fn_GetLBAexist' and type = 'FN')
	drop function fn_GetLBAexist
GO

SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO

---------------------------------------------------------------------
-----
-----	Proc Name:		fn_GetLBAexist
-----
-----	Version:		SQL Server 2005
-----
-----	Created:		Suneel Kumar Mogali
-----
-----	Description:	LBA exist or not
-----
-----	Modified:	
-----
---------------------------------------------------------------------
CREATE FUNCTION fn_GetLBAexist
(@ADJNO int)

RETURNS int 
AS
BEGIN

declare @Return int
set @Return = 0

SELECT @Return = count(1)
FROM PREM_ADJ INNER JOIN CUSTMR 
ON PREM_ADJ.reg_custmr_id = CUSTMR.CUSTMR_ID
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.CUSTMR_ID = PREM_ADJ.reg_custmr_id
AND PREM_ADJ_PGM.ACTV_IND = 1 
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ.PREM_ADJ_ID
AND PREM_ADJ_PERD.CUSTMR_ID = CUSTMR.CUSTMR_ID 
AND PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN EXTRNL_ORG ON EXTRNL_ORG.EXTRNL_ORG_ID = PREM_ADJ_PGM.BRKR_ID
INNER JOIN PREM_ADJ_PGM_SETUP ON PREM_ADJ_PGM_SETUP.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID 
AND PREM_ADJ_PGM_SETUP.CUSTMR_ID = PREM_ADJ.reg_custmr_id 
INNER JOIN COML_AGMT ON COML_AGMT.CUSTMR_ID = PREM_ADJ.reg_custmr_id AND COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PARMET_SETUP ON PREM_ADJ_PARMET_SETUP.CUSTMR_ID = PREM_ADJ.reg_custmr_id
AND PREM_ADJ_PARMET_SETUP.PREM_ADJ_PERD_ID = PREM_ADJ_PERD.PREM_ADJ_PERD_ID
AND PREM_ADJ_PARMET_SETUP.PREM_ADJ_ID = PREM_ADJ.PREM_ADJ_ID
AND PREM_ADJ_PARMET_SETUP.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PARMET_SETUP.PREM_ADJ_PGM_SETUP_ID = PREM_ADJ_PGM_SETUP.PREM_ADJ_PGM_SETUP_ID
INNER JOIN PREM_ADJ_PARMET_DTL ON PREM_ADJ_PARMET_DTL.PREM_ADJ_PARMET_SETUP_ID = PREM_ADJ_PARMET_SETUP.PREM_ADJ_PARMET_SETUP_ID
AND PREM_ADJ_PARMET_DTL.PREM_ADJ_PERD_ID = PREM_ADJ_PERD.PREM_ADJ_PERD_ID
AND PREM_ADJ_PARMET_DTL.PREM_ADJ_ID = PREM_ADJ.PREM_ADJ_ID
INNER JOIN LKUP ON LKUP.LKUP_ID = PREM_ADJ_PARMET_DTL.ST_ID
INNER JOIN PREM_ADJ_PGM_SETUP_POL ON PREM_ADJ_PGM_SETUP_POL.PREM_ADJ_PGM_SETUP_ID =
PREM_ADJ_PGM_SETUP.PREM_ADJ_PGM_SETUP_ID AND PREM_ADJ_PGM_SETUP_POL.PREM_ADJ_PGM_ID =
PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND PREM_ADJ_PGM_SETUP_POL.CUSTMR_ID = CUSTMR.CUSTMR_ID
AND PREM_ADJ_PGM_SETUP_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
LEFT OUTER JOIN PREM_ADJ_CMMNT ON PREM_ADJ.prem_adj_id = PREM_ADJ_CMMNT.prem_adj_id
AND PREM_ADJ_CMMNT.PREM_ADJ_PERD_ID = PREM_ADJ_PERD.PREM_ADJ_PERD_ID 
AND PREM_ADJ_CMMNT.CMMNT_CATG_ID = 320
INNER JOIN LKUP LKUP2 ON LKUP2.LKUP_ID = PREM_ADJ_PGM.PAID_INCUR_TYP_ID
INNER JOIN LKUP PGMTYP ON PGMTYP.LKUP_ID = PREM_ADJ_PGM.PGM_TYP_ID
 WHERE PREM_ADJ.PREM_ADJ_ID =  @ADJNO --AND COML_AGMT.ADJ_TYP_ID NOT IN (68) -- 62(Escrow) is removed from this condition as per anil discussed on 19 Feb 2009.
AND PREM_ADJ_PGM_SETUP.ADJ_PARMET_TYP_ID = 401


return @Return
end

go

if object_id('fn_GetLBAexist') is not null
	print 'Created function fn_GetLBAexist'
else
	print 'Failed function fn_GetLBAexist'
go

if object_id('fn_GetLBAexist') is not null
	grant exec on fn_GetLBAexist to public
go

