
truncate table QLTY_CNTRL_MSTR_ISSU_LIST
go

DBCC CHECKIDENT('QLTY_CNTRL_MSTR_ISSU_LIST', RESEED,1)

go

-- Account Setup QC Issues(223)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',223, 'Account Info Incorrect', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',223, 'Program Periods Incorrect', 0, 2, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',223, 'Policy/Parameters Incorrect', 0, 3, 1, 1)
-- Adjustment QC Issues(224)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',224, 'None', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',224, 'Account Info Incorrect', 0, 2, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',224, 'Program Periods Incorrect', 0, 3, 1, 1)
-- Recon QC Issues(225)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',225, 'No Changes', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',225, 'Billing Frequency Different', 0, 2, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',225, 'Incorrect/Missing Policy #', 0, 3, 1, 1)
-- ARiES Clearing QC Issues(226)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',226, 'None', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',226, 'Main / Sub Error', 0, 2, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',226, 'Reserve Amount Error', 0, 3, 1, 1)
-- 20% QC Issues(227)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',227, 'None', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',227, 'Account Info Incorrect', 0, 2, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',227, 'Program Periods Incorrect', 0, 3, 1, 1)
-- Account Setup Processing Checklist(228) - Part1
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '* Bundled Billing Form/TPA Notification:', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Insured Name', 0, 2, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Valuation Date', 0, 3, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Program Effective Date & Expiration Date', 0, 4, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '* For Initial Adjustments, read through the agreements, amendments & audits (front to back) to confirm that all relevant info is properly entered on the adjustment', 0, 5, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '* Read the Adjustment for Typos and Presentation. Confirm name and addresses', 0, 5, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '* Agreement: Heading - Insured Name and Type of Program', 0, 6, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Effective Date & Expiration Date', 0, 7, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Policy Numbers (Check adjustment & loss runs)', 0, 8, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Loss Limits & ALAE Handling', 0, 9, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           ULAE / ALAE erodes aggregate', 0, 10, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Retro and / or LRF Formula', 0, 11, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Minimum', 0, 12, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Maximum', 0, 13, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Basic', 0, 14, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Tax Multiplier', 0, 15, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Combined Elements', 0, 16, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           LBA''s (State and Rates)', 0, 17, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           LCF or Claim Handling Fee Rates', 0, 18, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           No. of months until first valuation Date', 0, 19, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Conversion Date', 0, 20, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '* Audit:  Check CESAR "01" screen for a "1" in Retro and "800" Producer #', 0, 21, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Confirm Policy #s on Audit', 0, 23, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Confirm that all loss states have premium on the audit', 0, 22, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Confirm that all payroll', 0, 24, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Confirm that Pay-in + Deferral="Deposit Premium"',0, 25, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Confirm Audit Result',0, 26, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           Confirm Total Subject Premium',0, 27, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',228, '           KY / OR Assessments',0, 28, 1, 1)
-- Adjustment Processing Checklist(229) - Part 1
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',229, '* ARMIS Loss Run', 0, 29, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',229, '* Tie out loss run to totals in adjustment (manual worksheet)', 0, 30, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',229, '* Audit:  Check CESAR "22" screen to confirm there are no audit revisions', 0, 31, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',229, '* Prove AP/RP(see separate worksheet)', 0, 32, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',229, '* Paid loss programs converting? Related deductible programs in LSI or manual TPA',0, 33, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',229, '* Check that coding is in Coding Transmittal Report and previous #s agree to CESAR',0, 34, 1, 1)

-- Adjustment Approved Invoice to Underwriting Checklist(230)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',230, 'Complete a new LSSI to Underwriting (transaction type "underwriter signoff" 8 day email reminder) requesting approval of adjustmetn (attach invoice copy).',0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',230, 'Also attach loss runs to support adjustment. (indicate release date).',0, 2, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',230, 'GC - Send only initial adjustment',0, 3, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',230, 'Send the entire adjustment to the underwriter',0, 4, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',230, 'No UW approval required',0, 5, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',230, 'All other BUs - Send entire adjustment',0, 6, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',230, 'Add resolve date to invoice to Collections pending reason',0, 7, 1, 1)

insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',223, 'Retro Info Incorrect', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',223, 'Loss Fund Info Incorrect', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',223, 'Missing/Incomplete Account Setup Processing Checklist', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',223, 'Other', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',223, 'None', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',224, 'Policy/Parameters Incorrect', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',224, 'Retro Info Incorrect', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',224, 'Loss Fund Info Incorrect', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',224, 'Missing/Incomplete Adj. Checklist', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',224, 'Other', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',227, 'Policy/Parameters Incorrect', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',227, 'Retro Info Incorrect', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',227, 'Loss Fund Info Incorrect', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',227, 'Missing/Incomplete Adj. Checklist', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',227, 'Other', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',225, 'LCF/LBA/TM Factors Different', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',225, 'Loss Limit Discrepancy', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',225, 'Missing Agreement', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',225, 'Incorrect Policy Year', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',225, 'Missing DEP Policy #', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',225, 'Program Type Discrepancies', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',225, 'Other', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',226, 'Coding Error', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',226, 'Worksheet Error', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',226, 'Worksheet Not Completed', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',226, 'AIS Transmittal Error', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',226, 'Uncleared Bookings', 0, 1, 1, 1)
insert into qlty_cntrl_mstr_issu_list (crte_dt,issu_catg_id, issu_txt, finc_ind, srt_nbr, crte_user_id, actv_ind) values('01/01/2008',226, 'Other', 0, 1, 1, 1)

