 
IF EXISTS (SELECT 1 FROM sysobjects 
	WHERE NAME = 'GetExcessLossExhibit' and TYPE = 'P')
	DROP PROC GetExcessLossExhibit
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO

---------------------------------------------------------------------
-----
-----	PROC NAME:		GetExcessLossExhibit
-----
-----	VERSION:		SQL SERVER 2005
-----
-----	AUTHOR :		SUNEEL KUMAR MOGALI
-----
-----	DESCRIPTION:	RETURNS DATA WITH RESPECT TO THE GIVEN INVOICE NUMBER.
-----			
-----	ON EXIT:	
-----			
-----
-----	MODIFIED:	Sreedhar Bobbili (24th March 2009)
-----			
----- 
---------------------------------------------------------------------

CREATE PROCEDURE [dbo].[GetExcessLossExhibit]
@ADJNO INT,
@FLAG INT,
@HISTFLAG BIT
AS
BEGIN

-- SET NOCOUNT ON added to prevent extra result sets from interfering with SELECT statements.
SET NOCOUNT ON;


BEGIN TRY

SELECT DISTINCT CASE @FLAG WHEN 1 THEN PREM_ADJ.DRFT_INVC_NBR_TXT 
WHEN 2 THEN PREM_ADJ.FNL_INVC_NBR_TXT 
ELSE PREM_ADJ.DRFT_INVC_NBR_TXT END "INVOICE NUMBER",
PREM_ADJ.FNL_INVC_DT "FINAL DATE",
CASE @FLAG WHEN 1 THEN CONVERT(NVARCHAR(30), DRFT_INVC_DT,101)
 WHEN 2 THEN CONVERT(NVARCHAR(30), FNL_INVC_DT,101)
ELSE  CONVERT(NVARCHAR(30), DRFT_INVC_DT,101) END "INVOICE DATE",
CONVERT(NVARCHAR(30), PREM_ADJ_PGM.STRT_DT, 101) + '-' + CONVERT(NVARCHAR(30), PREM_ADJ_PGM.PLAN_END_DT,101) "PROGRAM PERIOD",
CONVERT(NVARCHAR(30), PREM_ADJ.VALN_DT, 101) "VALUATION DATE",
CUSTMR.FULL_NM "INSURED NAME",
--INT_ORG.FULL_NAME+'/'+INT_ORG.CITY_NM "BU/OFFICE", 
PREM_ADJ_PGM.BRKR_ID "BROKER ID",
EXTRNL_ORG.FULL_NAME "BROKER",
--LKUP2.LKUP_TXT+'('+CASE WHEN PGMTYP.LKUP_TXT LIKE 'NON-DEP%' THEN 'Retro' ELSE PGMTYP.LKUP_TXT END +')'  "ADJUSTMENT TYPE",
--CASE WHEN COMLADJTYP.LKUP_TXT LIKE 'Paid%'  THEN 'Paid' WHEN COMLADJTYP.LKUP_TXT LIKE 'Incurred%' THEN 'Incurred' ELSE COMLADJTYP.LKUP_TXT END "ADJUSTMENT TYPE",
CASE WHEN COMLADJTYP.LKUP_TXT LIKE 'Paid%'  THEN 'Paid' WHEN COMLADJTYP.LKUP_TXT LIKE 'Incurred%' THEN 'Incurred' ELSE dbo.fn_GetILRFLossType(PREM_ADJ_PGM.PREM_ADJ_PGM_ID) END "ADJUSTMENT TYPE",
--dbo.fn_GetILRFLossType(PREM_ADJ_PGM.PREM_ADJ_PGM_ID)  "ADJUSTMENT TYPE",
PREM_ADJ_PERD.ADJ_NBR_TXT "ADJUSTMENT NUMBER",
COML_AGMT.POL_SYM_TXT + ' ' + RTRIM(COML_AGMT.POL_NBR_TXT) + '-' + COML_AGMT.POL_MODULUS_TXT "POLICY NUMBER",
LKUP.ATTR_1_TXT "LOB",
LKUP1.ATTR_1_TXT "STATE",
CASE ARMIS_LOS_EXC.addn_clm_ind WHEN 0 THEN ARMIS_LOS_EXC.CLM_NBR_TXT 
WHEN 1 THEN ARMIS_LOS_EXC.CLM_NBR_TXT + ',' + isnull(ARMIS_LOS_EXC.addn_clm_txt,'')
END  "CLAIM",
ARMIS_LOS_EXC.PAID_IDNMTY_AMT "PIA",
ARMIS_LOS_EXC.PAID_EXPS_AMT "PEA",
ARMIS_LOS_EXC.RESRVD_IDNMTY_AMT "RIA",
ARMIS_LOS_EXC.RESRVD_EXPS_AMT "REA",
ARMIS_LOS_EXC.non_bilabl_paid_idnmty_amt "NPIA",
ARMIS_LOS_EXC.non_bilabl_paid_exps_amt "NPEA",
ARMIS_LOS_EXC.non_bilabl_resrvd_idnmty_amt "NRIA",
ARMIS_LOS_EXC.non_bilabl_resrvd_exps_amt "NREA",
ARMIS_LOS_EXC.subj_paid_exps_amt "SPEA",
ARMIS_LOS_EXC.subj_paid_idnmty_amt "SPIA",
ARMIS_LOS_EXC.subj_resrvd_idnmty_amt "SRIA",
ARMIS_LOS_EXC.subj_resrvd_exps_amt "SREA",
ARMIS_LOS_EXC.exc_paid_idnmty_amt "EPIA",
ARMIS_LOS_EXC.exc_paid_exps_amt "EPEA",
ARMIS_LOS_EXC.exc_resrvd_idnmty_amt "ERIA",
ARMIS_LOS_EXC.exc_resrvd_exps_amt "EREA",
ARMIS_LOS_EXC.subj_ldf_ibnr_amt "LDF",
PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PREM ADJ PERD ID",
PREM_ADJ_CMMNT.CMMNT_TXT "COMMENTS",
PREM_ADJ.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM ADJ PGM ID"
FROM PREM_ADJ 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ.PREM_ADJ_ID
AND PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN CUSTMR ON PREM_ADJ_PERD.CUSTMR_ID = CUSTMR.CUSTMR_ID
INNER JOIN EXTRNL_ORG ON EXTRNL_ORG.EXTRNL_ORG_ID = PREM_ADJ_PGM.BRKR_ID
--INNER JOIN INT_ORG ON INT_ORG.INT_ORG_ID = PREM_ADJ_PGM.BSN_UNT_OFC_ID
INNER JOIN COML_AGMT ON COML_AGMT.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND COML_AGMT.CUSTMR_ID = CUSTMR.CUSTMR_ID AND COML_AGMT.ACTV_IND = 1
INNER JOIN LKUP ON LKUP.LKUP_ID = COML_AGMT.COVG_TYP_ID
INNER JOIN ARMIS_LOS_POL ON ARMIS_LOS_POL.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
AND ARMIS_LOS_POL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND ARMIS_LOS_POL.CUSTMR_ID = CUSTMR.CUSTMR_ID
AND ARMIS_LOS_POL.PREM_ADJ_ID = PREM_ADJ.PREM_ADJ_ID
AND ARMIS_LOS_POL.ACTV_IND = 1
INNER JOIN ARMIS_LOS_EXC ON ARMIS_LOS_EXC.ARMIS_LOS_POL_ID = ARMIS_LOS_POL.ARMIS_LOS_POL_ID
AND ARMIS_LOS_EXC.COML_AGMT_ID = COML_AGMT.COML_AGMT_ID
AND ARMIS_LOS_EXC.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND ARMIS_LOS_EXC.CUSTMR_ID = CUSTMR.CUSTMR_ID
AND ARMIS_LOS_EXC.ACTV_IND = 1
INNER JOIN LKUP LKUP1 ON LKUP1.LKUP_ID = ARMIS_LOS_POL.ST_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
LEFT OUTER JOIN PREM_ADJ_CMMNT ON PREM_ADJ.prem_adj_id = PREM_ADJ_CMMNT.prem_adj_id
AND PREM_ADJ_CMMNT.PREM_ADJ_PERD_ID = PREM_ADJ_PERD.PREM_ADJ_PERD_ID 
AND PREM_ADJ_CMMNT.CMMNT_CATG_ID = 450
INNER JOIN LKUP LKUP2 ON LKUP2.LKUP_ID = PREM_ADJ_PGM.PAID_INCUR_TYP_ID
INNER JOIN LKUP PGMTYP ON PGMTYP.LKUP_ID = PREM_ADJ_PGM.PGM_TYP_ID
INNER JOIN LKUP COMLADJTYP ON COMLADJTYP.LKUP_ID = COML_AGMT.ADJ_TYP_ID
 WHERE PREM_ADJ.PREM_ADJ_ID =  @ADJNO 
--and (LKUP1.ATTR_1_TXT <> 'FL' and PREM_ADJ_PGM.PREM_ADJ_PGM_ID=940)



END TRY
BEGIN CATCH

 
 SELECT 
    ERROR_NUMBER() AS ERRORNUMBER,
    ERROR_SEVERITY() AS ERRORSEVERITY,
    ERROR_STATE() AS ERRORSTATE,
    ERROR_PROCEDURE() AS ERRORPROCEDURE,
    ERROR_LINE() AS ERRORLINE,
    ERROR_MESSAGE() AS ERRORMESSAGE;


END CATCH
END


GO

IF OBJECT_ID('GetExcessLossExhibit') IS NOT NULL
	PRINT 'CREATED PROCEDURE GetExcessLossExhibit'
ELSE
	PRINT 'FAILED CREATING PROCEDURE GetExcessLossExhibit'
GO

IF OBJECT_ID('GetExcessLossExhibit') IS NOT NULL
	GRANT EXEC ON GetExcessLossExhibit TO PUBLIC
GO










