
IF EXISTS (SELECT 1 FROM sysobjects 
	WHERE NAME = 'GetRetroSummary' and TYPE = 'P')
	DROP PROC GetRetroSummary
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO

---------------------------------------------------------------------
-----
-----	PROC NAME:		GetRetroSummary
-----
-----	VERSION:		SQL SERVER 2005
-----
-----	AUTHOR :		SUNEEL KUMAR MOGALI
-----
-----	DESCRIPTION:	RETURNS DATA WITH RESPECT TO THE GIVEN INVOICE NUMBER.
-----			
-----	ON EXIT:	
-----			
-----
-----	MODIFIED:	
-----			
----- 
---------------------------------------------------------------------

CREATE PROCEDURE [dbo].[GetRetroSummary]
@ADJNO INT,
@FLAG INT,
@HISTFLAG BIT
AS
BEGIN

-- SET NOCOUNT ON added to prevent extra result sets from interfering with SELECT statements.
SET NOCOUNT ON;

BEGIN TRY




--1
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'1' "NUMERICVALUE",
'Incurred Limited Losses' "DESCRIPTION",
SUM(ISNULL(PREM_ADJ_RETRO_DTL.SUBJ_PAID_IDNMTY_AMT,0)+
ISNULL(PREM_ADJ_RETRO_DTL.SUBJ_RESRV_IDNMTY_AMT,0)) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
into #tmpRetro
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID
AND COML_AGMT.ADJ_TYP_ID NOT IN (67,72,66,73) AND COML_AGMT.ACTV_IND = 1

WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID
UNION ALL 
--2
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'2' "NUMERICVALUE",
'Incurred Limited Allocated Loss Adjustment Expense(ALAE)' "DESCRIPTION",
SUM(CASE WHEN PREM_ADJ_RETRO_DTL.SUBJ_PAID_EXPS_AMT IS NULL 
THEN 0 ELSE PREM_ADJ_RETRO_DTL.SUBJ_PAID_EXPS_AMT END +
CASE WHEN PREM_ADJ_RETRO_DTL.SUBJ_RESRV_EXPS_AMT IS NULL 
THEN 0 ELSE PREM_ADJ_RETRO_DTL.SUBJ_RESRV_EXPS_AMT END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID
UNION ALL 
--3
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'3' "NUMERICVALUE",
'Unallocated Loss Adjustment Expense(ULAE)' "DESCRIPTION",
SUM(ISNULL(PREM_ADJ_RETRO_DTL.LOS_CONV_FCTR_AMT,0)+ ISNULL(PREM_ADJ_RETRO_DTL.CLM_HNDL_FEE_AMT,0)) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL 
--4
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'4' "NUMERICVALUE",
'Loss Based Assessment' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.LOS_BASE_ASESSMENT_AMT) <> 0 THEN 
SUM(CASE PREM_ADJ_RETRO_DTL.LOS_BASE_ASESSMENT_AMT
WHEN NULL THEN 0 
ELSE PREM_ADJ_RETRO_DTL.LOS_BASE_ASESSMENT_AMT END
) ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL 
--5
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'5' "NUMERICVALUE",
'Loss Development Reserve' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.LOS_DEV_RESRV_AMT) <> 0 THEN
SUM(CASE PREM_ADJ_RETRO_DTL.LOS_DEV_RESRV_AMT
WHEN NULL THEN 0 
ELSE PREM_ADJ_RETRO_DTL.LOS_DEV_RESRV_AMT END
) ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL 
--6
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'6' "NUMERICVALUE",
'Excess Loss Premium' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.EXC_LOS_PREM_AMT) <> 0 THEN
SUM(CASE PREM_ADJ_RETRO_DTL.EXC_LOS_PREM_AMT
WHEN NULL THEN 0 
ELSE PREM_ADJ_RETRO_DTL.EXC_LOS_PREM_AMT END
) ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL 
--7
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'7' "NUMERICVALUE",
'Residual Market Charge' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.RSDL_MKT_LOAD_TOT_AMT) <> 0 THEN
SUM(CASE PREM_ADJ_RETRO_DTL.RSDL_MKT_LOAD_TOT_AMT
WHEN NULL THEN 0 
ELSE PREM_ADJ_RETRO_DTL.RSDL_MKT_LOAD_TOT_AMT END
) ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID
AND COML_AGMT.ADJ_TYP_ID IN (66,73) AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL 
--8
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'8' "NUMERICVALUE",
'Non-conversion Assessment' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.NON_CONV_FEE_AMT) <> 0 THEN
SUM(CASE PREM_ADJ_RETRO_DTL.NON_CONV_FEE_AMT
WHEN NULL THEN 0 
ELSE PREM_ADJ_RETRO_DTL.NON_CONV_FEE_AMT END
) ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL
--9
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'9' "NUMERICVALUE",
'Other Adjustment Amount(see exhibit)' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.OTHR_AMT) <> 0 THEN
SUM(CASE PREM_ADJ_RETRO_DTL.OTHR_AMT
WHEN NULL THEN 0 
ELSE PREM_ADJ_RETRO_DTL.OTHR_AMT END
) ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL
--10
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'10' "NUMERICVALUE",
'Basic Premium' "DESCRIPTION",
SUM(CASE WHEN PREM_ADJ_RETRO_DTL.BASIC_AMT IS NULL 
THEN 0 ELSE PREM_ADJ_RETRO_DTL.BASIC_AMT END) "FINAL VALUE",
0 "UNLIM FLAG",
PREM_ADJ_PGM_RETRO.retro_adj_fctr_aplcbl_ind "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN PREM_ADJ_PGM_RETRO ON PREM_ADJ_PGM.PREM_ADJ_PGM_ID = PREM_ADJ_PGM_RETRO.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_RETRO.RETRO_ELEMT_TYP_ID = 334
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID,PREM_ADJ_PGM_RETRO.retro_adj_fctr_aplcbl_ind
UNION ALL
--11
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'11' "NUMERICVALUE",
'Premium Tax' "DESCRIPTION",
SUM(CASE WHEN PREM_ADJ_RETRO_DTL.PREM_TAX_AMT IS NULL 
THEN 0 ELSE PREM_ADJ_RETRO_DTL.PREM_TAX_AMT END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL
--12
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'12' "NUMERICVALUE",
'Earned Retrospective Premium (ERP)' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT) <> 0 THEN
(SUM(CASE WHEN PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT IS NULL 
THEN 0 ELSE PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT END)) 
ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID
AND COML_AGMT.ADJ_TYP_ID NOT IN (66,73) AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL
--13 EDP
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'13' "NUMERICVALUE",
'Earned Deductible Premium (EDP)' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT) <> 0 THEN
(SUM(CASE WHEN PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT IS NULL 
THEN 0-isnull(PREM_ADJ_RETRO_DTL.prem_asses_amt,0) 
ELSE PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT-
isnull(PREM_ADJ_RETRO_DTL.prem_asses_amt,0) END)) 
ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID
AND COML_AGMT.ADJ_TYP_ID IN (66,73) AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL
--14
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'14' "NUMERICVALUE",
'Adjustable WC Deductible Losses' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.adj_dedtbl_wrk_comp_los_amt) <> 0 THEN
SUM(CASE PREM_ADJ_RETRO_DTL.adj_dedtbl_wrk_comp_los_amt
WHEN NULL THEN 0 
ELSE PREM_ADJ_RETRO_DTL.adj_dedtbl_wrk_comp_los_amt END
) ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL
-- INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID
AND COML_AGMT.ADJ_TYP_ID IN (66,73,67,72) AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL
--15 ADJ WC ASSESS
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'15' "NUMERICVALUE",
'Adjustable WC Assessment' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.prem_asses_amt) <> 0 THEN
SUM(CASE PREM_ADJ_RETRO_DTL.prem_asses_amt
WHEN NULL THEN 0 
ELSE PREM_ADJ_RETRO_DTL.prem_asses_amt END
) ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID
AND COML_AGMT.ADJ_TYP_ID IN (66,73) AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL
--16 RETRO COST
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'16' "NUMERICVALUE",
'Total Earned Retrospective Cost' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT) <> 0  
AND COUNT(PREM_ADJ_RETRO_DTL.adj_dedtbl_wrk_comp_los_amt) <> 0 THEN
(SUM(CASE WHEN PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT IS NULL 
THEN 0 ELSE PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT END) + 
SUM(CASE PREM_ADJ_RETRO_DTL.adj_dedtbl_wrk_comp_los_amt
WHEN NULL THEN 0 
ELSE PREM_ADJ_RETRO_DTL.adj_dedtbl_wrk_comp_los_amt END
)) ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID
AND COML_AGMT.ADJ_TYP_ID NOT IN (66,73) AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL
--17 RETRO DED PREM
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Adjustment' "GRP NAME",
'17' "NUMERICVALUE",
'Total Earned Deductible Premium' "DESCRIPTION",
(CASE WHEN COUNT(PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT) <> 0  
AND (COUNT(PREM_ADJ_RETRO_DTL.adj_dedtbl_wrk_comp_los_amt) <> 0 
OR COUNT(PREM_ADJ_RETRO_DTL.prem_asses_amt) <> 0) THEN
(SUM(CASE WHEN PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT IS NULL 
THEN 0-isnull(PREM_ADJ_RETRO_DTL.prem_asses_amt ,0)
ELSE PREM_ADJ_RETRO_DTL.ADJ_INCUR_ERND_RETRO_PREM_AMT-isnull(PREM_ADJ_RETRO_DTL.prem_asses_amt,0) END) + 
ISNULL(SUM(CASE PREM_ADJ_RETRO_DTL.adj_dedtbl_wrk_comp_los_amt
WHEN NULL THEN 0 ELSE PREM_ADJ_RETRO_DTL.adj_dedtbl_wrk_comp_los_amt END
),0)+ ISNULL(SUM(CASE PREM_ADJ_RETRO_DTL.prem_asses_amt
WHEN NULL THEN 0 ELSE PREM_ADJ_RETRO_DTL.prem_asses_amt END
),0)) ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID
AND COML_AGMT.ADJ_TYP_ID IN (66,73) AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL
--18 
SELECT PREM_ADJ_PERD.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Minimum / Maximum Application' "GRP NAME",
'18' "NUMERICVALUE",
'Minimum' "DESCRIPTION",
case when isnull(tot_agmt_amt,0) > isnull(tot_audt_amt,0) 
then isnull(tot_agmt_amt,0) else isnull(tot_audt_amt,0) end "FINAL VALUE",
PREM_ADJ_PGM_RETRO.no_lim_ind "UNLIM FLAG",
PREM_ADJ_PGM_RETRO.retro_adj_fctr_aplcbl_ind "NA",
PREM_ADJ_PERD.ernd_retro_prem_min_max_cd "MIN MAX CODE"
FROM PREM_ADJ_PERD
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN PREM_ADJ_PGM_RETRO ON PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM_RETRO.PREM_ADJ_PGM_ID
WHERE PREM_ADJ_PERD.PREM_ADJ_ID =  @ADJNO AND 
PREM_ADJ_PGM_RETRO.RETRO_ELEMT_TYP_ID = 338  
UNION ALL
--19
SELECT PREM_ADJ_PERD.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Minimum / Maximum Application' "GRP NAME",
'19' "NUMERICVALUE",
CASE PREM_ADJ_PGM_RETRO.EXPO_TYP_ID WHEN 128 THEN 'Combined Elements' 
ELSE 'Maximum' END "DESCRIPTION",
case when isnull(tot_agmt_amt,0) > isnull(tot_audt_amt,0) 
then isnull(tot_agmt_amt,0) else isnull(tot_audt_amt,0) end "FINAL VALUE",
PREM_ADJ_PGM_RETRO.no_lim_ind "UNLIM FLAG",
PREM_ADJ_PGM_RETRO.retro_adj_fctr_aplcbl_ind "NA",
PREM_ADJ_PERD.ernd_retro_prem_min_max_cd "MIN MAX CODE"
FROM PREM_ADJ_PGM_RETRO INNER JOIN PREM_ADJ_PERD 
ON PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM_RETRO.PREM_ADJ_PGM_ID
AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_PGM_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_PERD.PREM_ADJ_ID =  @ADJNO AND 
PREM_ADJ_PGM_RETRO.RETRO_ELEMT_TYP_ID = 337  
UNION ALL
--20
SELECT PREM_ADJ_PERD.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Minimum / Maximum Application' "GRP NAME",
'20' "NUMERICVALUE",
'If ERP is less than Minimum, Minimum applies' "DESCRIPTION",
CASE WHEN PREM_ADJ_PERD.ernd_retro_prem_min_max_cd = 'Max' THEN PREM_ADJ_PERD.ernd_retro_prem_max_amt
WHEN  PREM_ADJ_PERD.ernd_retro_prem_min_max_cd = 'Min' THEN PREM_ADJ_PERD.ernd_retro_prem_min_amt 
WHEN PREM_ADJ_PERD.ernd_retro_prem_min_max_cd = 'ERP' THEN PREM_ADJ_PERD.ernd_retro_prem_amt ELSE NULL END "FINAL VALUE",
PREM_ADJ_PERD.ernd_retro_prem_unlim_ind "UNLIM FLAG",
0 "NA",
PREM_ADJ_PERD.ernd_retro_prem_min_max_cd "MIN MAX CODE"
FROM PREM_ADJ_PERD 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_PERD.PREM_ADJ_ID =  @ADJNO
UNION ALL
--21
SELECT PREM_ADJ_PERD.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Minimum / Maximum Application' "GRP NAME",
'21' "NUMERICVALUE",
'If ERP is greater than Maximum, Maximum applies' "DESCRIPTION",
CASE WHEN PREM_ADJ_PERD.ernd_retro_prem_min_max_cd = 'Max' THEN PREM_ADJ_PERD.ernd_retro_prem_max_amt
WHEN  PREM_ADJ_PERD.ernd_retro_prem_min_max_cd = 'Min' THEN PREM_ADJ_PERD.ernd_retro_prem_min_amt 
WHEN PREM_ADJ_PERD.ernd_retro_prem_min_max_cd = 'ERP' THEN PREM_ADJ_PERD.ernd_retro_prem_amt ELSE NULL END "FINAL VALUE",
PREM_ADJ_PERD.ernd_retro_prem_unlim_ind "UNLIM FLAG",
0 "NA",
PREM_ADJ_PERD.ernd_retro_prem_min_max_cd "MIN MAX CODE"
FROM PREM_ADJ_PERD 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_PERD.PREM_ADJ_ID =  @ADJNO
UNION ALL
--22
SELECT PREM_ADJ_PERD.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Minimum / Maximum Application' "GRP NAME",
'22' "NUMERICVALUE",
'If ERP is greater than Minimum, but less than Maximum, ERP applies' "DESCRIPTION",
CASE WHEN PREM_ADJ_PERD.ernd_retro_prem_min_max_cd = 'Max' THEN PREM_ADJ_PERD.ernd_retro_prem_max_amt
WHEN  PREM_ADJ_PERD.ernd_retro_prem_min_max_cd = 'Min' THEN PREM_ADJ_PERD.ernd_retro_prem_min_amt 
WHEN PREM_ADJ_PERD.ernd_retro_prem_min_max_cd = 'ERP' THEN PREM_ADJ_PERD.ernd_retro_prem_amt ELSE NULL END "FINAL VALUE",
PREM_ADJ_PERD.ernd_retro_prem_unlim_ind "UNLIM FLAG",
0 "NA",
PREM_ADJ_PERD.ernd_retro_prem_min_max_cd "MIN MAX CODE"
FROM PREM_ADJ_PERD 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_PERD.PREM_ADJ_ID =  @ADJNO
UNION ALL
--23
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Credit for Premium and Losses*' "GRP NAME",
'23' "NUMERICVALUE",
'Standard (Subject) Premium Deposit' "DESCRIPTION",
-(CASE WHEN COUNT(PREM_ADJ_RETRO.SUBJ_DEPST_PREM_AMT) <> 0  THEN
SUM(CASE WHEN PREM_ADJ_RETRO.SUBJ_DEPST_PREM_AMT IS NULL THEN 0 
ELSE PREM_ADJ_RETRO.SUBJ_DEPST_PREM_AMT END) 
ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO.COML_AGMT_ID and COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID
UNION ALL
--24
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Credit for Premium and Losses*' "GRP NAME",
'24' "NUMERICVALUE",
'Prior ERP' "DESCRIPTION",
-(CASE WHEN COUNT(PREM_ADJ_RETRO.PREV_ERND_RETRO_PREM_AMT) <> 0  THEN
SUM(CASE WHEN PREM_ADJ_RETRO.PREV_ERND_RETRO_PREM_AMT IS NULL THEN 0 
ELSE PREM_ADJ_RETRO.PREV_ERND_RETRO_PREM_AMT END) 
ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO.COML_AGMT_ID
AND COML_AGMT.ADJ_TYP_ID NOT IN (66,73) --AND COML_AGMT.ACTV_IND = 1--(11283 Bug Fix)
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID
UNION ALL
--25 Prior EDP
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Credit for Premium and Losses*' "GRP NAME",
'25' "NUMERICVALUE",
'Prior EDP' "DESCRIPTION",
-(CASE WHEN COUNT(PREM_ADJ_RETRO.PREV_ERND_RETRO_PREM_AMT) <> 0  THEN
SUM(CASE WHEN PREM_ADJ_RETRO.PREV_ERND_RETRO_PREM_AMT IS NULL THEN 0 
ELSE PREM_ADJ_RETRO.PREV_ERND_RETRO_PREM_AMT END) 
ELSE NULL END) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO.COML_AGMT_ID
AND COML_AGMT.ADJ_TYP_ID IN (66,73) --AND COML_AGMT.ACTV_IND = 1--(11283 Bug Fix)
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID
UNION ALL
--26
SELECT 
PREM_ADJ_PERD.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Credit for Premium and Losses*' "GRP NAME",
'26' "NUMERICVALUE",
'PEO Deposit' "DESCRIPTION",
-(PREM_ADJ_PGM.PEO_PAY_IN_AMT) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_PERD 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN CUSTMR ON CUSTMR.CUSTMR_ID = PREM_ADJ_PERD.CUSTMR_ID
WHERE PREM_ADJ_PERD.PREM_ADJ_ID =  @ADJNO AND CUSTMR.PEO_IND = 1
AND dbo.fn_GetCheckforRetro(PREM_ADJ_PERD.PREM_ADJ_ID,PREM_ADJ_PERD.PREM_ADJ_PGM_ID) = 1
UNION ALL
--27 PLB for CURR ADj PERD
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Credit for Premium and Losses*' "GRP NAME",
'27' "NUMERICVALUE",
'Paid Loss Billings for Current Adjustment Period' "DESCRIPTION",
-(SUM(PREM_ADJ_RETRO.PAID_LOS_BIL_AMT)) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID
UNION ALL
--28 Credit for Est Paid Losses
SELECT PREM_ADJ_MISC_INVC.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PERD.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Credit for Premium and Losses*' "GRP NAME",
'28' "NUMERICVALUE",
POST_TRNS_TYP.TRNS_NM_TXT "DESCRIPTION",
(PREM_ADJ_MISC_INVC.POST_AMT) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM POST_TRNS_TYP INNER JOIN PREM_ADJ_MISC_INVC ON
POST_TRNS_TYP.POST_TRNS_TYP_ID = PREM_ADJ_MISC_INVC.POST_TRNS_TYP_ID
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_PERD_ID = 
PREM_ADJ_MISC_INVC.PREM_ADJ_PERD_ID
inner join dbo.COML_AGMT on (COML_AGMT.pol_sym_txt = PREM_ADJ_MISC_INVC.pol_sym_txt) 
and (COML_AGMT.pol_nbr_txt = PREM_ADJ_MISC_INVC.pol_nbr_txt) 
and (COML_AGMT.pol_modulus_txt = PREM_ADJ_MISC_INVC.pol_modulus_txt) 
and coml_agmt.actv_ind = 1
WHERE POST_TRNS_TYP.TRNS_TYP_ID = 444 
 AND PREM_ADJ_MISC_INVC.PREM_ADJ_ID = @ADJNO
 AND POST_TRNS_TYP.adj_sumry_ind = 1
 AND POST_TRNS_TYP.ACTV_IND = 1 
 AND POST_TRNS_TYP.pol_reqr_ind = 1
 AND POST_TRNS_TYP.POST_TRNS_TYP_ID = 3 
 AND PREM_ADJ_MISC_INVC.ACTV_IND = 1 
    AND dbo.fn_GetCheckforRetro(PREM_ADJ_MISC_INVC.PREM_ADJ_ID,PREM_ADJ_PERD.PREM_ADJ_PGM_ID) = 1
UNION ALL
--29 Prior credit fot est losses
SELECT PREM_ADJ_MISC_INVC.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PERD.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Credit for Premium and Losses*' "GRP NAME",
'29' "NUMERICVALUE",
POST_TRNS_TYP.TRNS_NM_TXT "DESCRIPTION",
PREM_ADJ_MISC_INVC.POST_AMT "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM POST_TRNS_TYP INNER JOIN PREM_ADJ_MISC_INVC ON
POST_TRNS_TYP.POST_TRNS_TYP_ID = PREM_ADJ_MISC_INVC.POST_TRNS_TYP_ID
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_PERD_ID = 
PREM_ADJ_MISC_INVC.PREM_ADJ_PERD_ID
inner join dbo.COML_AGMT on (COML_AGMT.pol_sym_txt = PREM_ADJ_MISC_INVC.pol_sym_txt) 
and (COML_AGMT.pol_nbr_txt = PREM_ADJ_MISC_INVC.pol_nbr_txt) 
and (COML_AGMT.pol_modulus_txt = PREM_ADJ_MISC_INVC.pol_modulus_txt) 
and coml_agmt.actv_ind = 1
WHERE POST_TRNS_TYP.TRNS_TYP_ID = 444 
 AND PREM_ADJ_MISC_INVC.PREM_ADJ_ID = @ADJNO
 AND POST_TRNS_TYP.adj_sumry_ind = 1
 AND POST_TRNS_TYP.ACTV_IND = 1 
 AND PREM_ADJ_MISC_INVC.ACTV_IND = 1 
 AND POST_TRNS_TYP.pol_reqr_ind = 1
 AND POST_TRNS_TYP.POST_TRNS_TYP_ID = 4 AND
 dbo.fn_GetCheckforRetro(PREM_ADJ_MISC_INVC.PREM_ADJ_ID,PREM_ADJ_PERD.PREM_ADJ_PGM_ID) = 1
UNION ALL
--30 Total Credit, This we need to sum it up from 23 to 28
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Credit for Premium and Losses*' "GRP NAME",
'30' "NUMERICVALUE",
'Total Credit for Premium and Losses' "DESCRIPTION",
0 "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID
UNION ALL
--31 Excess Loss
SELECT PREM_ADJ_MISC_INVC.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PERD.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Other Charges' "GRP NAME",
'31' "NUMERICVALUE",
POST_TRNS_TYP.TRNS_NM_TXT "DESCRIPTION",
PREM_ADJ_MISC_INVC.POST_AMT "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM POST_TRNS_TYP INNER JOIN PREM_ADJ_MISC_INVC ON
POST_TRNS_TYP.POST_TRNS_TYP_ID = PREM_ADJ_MISC_INVC.POST_TRNS_TYP_ID
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_PERD_ID = 
PREM_ADJ_MISC_INVC.PREM_ADJ_PERD_ID
inner join dbo.COML_AGMT on (COML_AGMT.pol_sym_txt = PREM_ADJ_MISC_INVC.pol_sym_txt) 
and (COML_AGMT.pol_nbr_txt = PREM_ADJ_MISC_INVC.pol_nbr_txt) 
and (COML_AGMT.pol_modulus_txt = PREM_ADJ_MISC_INVC.pol_modulus_txt) 
and coml_agmt.actv_ind = 1
WHERE POST_TRNS_TYP.TRNS_TYP_ID = 444 
 AND PREM_ADJ_MISC_INVC.PREM_ADJ_ID = @ADJNO
 AND POST_TRNS_TYP.adj_sumry_ind = 1
 AND POST_TRNS_TYP.ACTV_IND = 1 
 AND POST_TRNS_TYP.pol_reqr_ind = 1
 AND PREM_ADJ_MISC_INVC.ACTV_IND = 1 
 AND POST_TRNS_TYP.POST_TRNS_TYP_ID = 11 AND dbo.fn_GetCheckforRetro(PREM_ADJ_MISC_INVC.PREM_ADJ_ID,PREM_ADJ_PERD.PREM_ADJ_PGM_ID) = 1
UNION ALL
--32 Insurance Charge
SELECT PREM_ADJ_MISC_INVC.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PERD.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Other Charges' "GRP NAME",
'32' "NUMERICVALUE",
POST_TRNS_TYP.TRNS_NM_TXT "DESCRIPTION",
PREM_ADJ_MISC_INVC.POST_AMT "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM POST_TRNS_TYP INNER JOIN PREM_ADJ_MISC_INVC ON
POST_TRNS_TYP.POST_TRNS_TYP_ID = PREM_ADJ_MISC_INVC.POST_TRNS_TYP_ID
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_PERD_ID = 
PREM_ADJ_MISC_INVC.PREM_ADJ_PERD_ID
inner join dbo.COML_AGMT on (COML_AGMT.pol_sym_txt = PREM_ADJ_MISC_INVC.pol_sym_txt) 
and (COML_AGMT.pol_nbr_txt = PREM_ADJ_MISC_INVC.pol_nbr_txt) 
and (COML_AGMT.pol_modulus_txt = PREM_ADJ_MISC_INVC.pol_modulus_txt) 
and coml_agmt.actv_ind = 1
WHERE POST_TRNS_TYP.TRNS_TYP_ID = 444 
 AND PREM_ADJ_MISC_INVC.PREM_ADJ_ID = @ADJNO
 AND POST_TRNS_TYP.adj_sumry_ind = 1
 AND POST_TRNS_TYP.ACTV_IND = 1 
 AND POST_TRNS_TYP.pol_reqr_ind = 1
 AND PREM_ADJ_MISC_INVC.ACTV_IND = 1 
 AND POST_TRNS_TYP.POST_TRNS_TYP_ID = 12 AND dbo.fn_GetCheckforRetro(PREM_ADJ_MISC_INVC.PREM_ADJ_ID,PREM_ADJ_PERD.PREM_ADJ_PGM_ID) = 1
UNION ALL
--33 Other Special Charges
SELECT PREM_ADJ_MISC_INVC.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PERD.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Other Charges' "GRP NAME",
'33' "NUMERICVALUE",
POST_TRNS_TYP.TRNS_NM_TXT "DESCRIPTION",
PREM_ADJ_MISC_INVC.POST_AMT "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM POST_TRNS_TYP INNER JOIN PREM_ADJ_MISC_INVC ON
POST_TRNS_TYP.POST_TRNS_TYP_ID = PREM_ADJ_MISC_INVC.POST_TRNS_TYP_ID
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_PERD_ID = 
PREM_ADJ_MISC_INVC.PREM_ADJ_PERD_ID
inner join dbo.COML_AGMT on (COML_AGMT.pol_sym_txt = PREM_ADJ_MISC_INVC.pol_sym_txt) 
and (COML_AGMT.pol_nbr_txt = PREM_ADJ_MISC_INVC.pol_nbr_txt) 
and (COML_AGMT.pol_modulus_txt = PREM_ADJ_MISC_INVC.pol_modulus_txt) 
and coml_agmt.actv_ind = 1
WHERE POST_TRNS_TYP.TRNS_TYP_ID = 444 
 AND PREM_ADJ_MISC_INVC.PREM_ADJ_ID = @ADJNO
 AND POST_TRNS_TYP.adj_sumry_ind = 1
 AND POST_TRNS_TYP.ACTV_IND = 1 
 AND POST_TRNS_TYP.pol_reqr_ind = 1
 AND PREM_ADJ_MISC_INVC.ACTV_IND = 1 
 AND POST_TRNS_TYP.POST_TRNS_TYP_ID = 13 AND dbo.fn_GetCheckforRetro(PREM_ADJ_MISC_INVC.PREM_ADJ_ID,PREM_ADJ_PERD.PREM_ADJ_PGM_ID) = 1
UNION ALL
--34 Total Other Charges, This we need to sum it up 31,32,33
SELECT PREM_ADJ_MISC_INVC.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PERD.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Other Charges' "GRP NAME",
'34' "NUMERICVALUE",
'Total Other Charges' "DESCRIPTION",
SUM(PREM_ADJ_MISC_INVC.POST_AMT) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM POST_TRNS_TYP INNER JOIN PREM_ADJ_MISC_INVC ON
POST_TRNS_TYP.POST_TRNS_TYP_ID = PREM_ADJ_MISC_INVC.POST_TRNS_TYP_ID
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_PERD_ID = 
PREM_ADJ_MISC_INVC.PREM_ADJ_PERD_ID
inner join dbo.COML_AGMT on (COML_AGMT.pol_sym_txt = PREM_ADJ_MISC_INVC.pol_sym_txt) 
and (COML_AGMT.pol_nbr_txt = PREM_ADJ_MISC_INVC.pol_nbr_txt) 
and (COML_AGMT.pol_modulus_txt = PREM_ADJ_MISC_INVC.pol_modulus_txt) 
and coml_agmt.actv_ind = 1
WHERE POST_TRNS_TYP.TRNS_TYP_ID = 444 
 AND PREM_ADJ_MISC_INVC.PREM_ADJ_ID = @ADJNO
 AND POST_TRNS_TYP.adj_sumry_ind = 1
 AND POST_TRNS_TYP.ACTV_IND = 1 
 AND POST_TRNS_TYP.pol_reqr_ind = 1
 AND PREM_ADJ_MISC_INVC.ACTV_IND = 1 
 AND POST_TRNS_TYP.POST_TRNS_TYP_ID IN (11,12,13)
GROUP BY PREM_ADJ_MISC_INVC.PREM_ADJ_ID,PREM_ADJ_PERD.PREM_ADJ_PGM_ID
UNION ALL
--35 Sum it up 20 or 21 or 22 and 30 and 34   
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Other Charges' "GRP NAME",
'35' "NUMERICVALUE",
'Sum of Min/Max Compare, Total Credit for Prem & Losses & if applicable, Other Charges' "DESCRIPTION",
0 "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
NULL "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID
UNION ALL
--36 Min & Max
--SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
--PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
--'Additional Credits and Charges' "GRP NAME",
--'36' "NUMERICVALUE",
--'Cash Flow Benefit' "DESCRIPTION",
--(SUM(PREM_ADJ_RETRO_DTL.ADJ_CASH_FLW_BEN_AMT)) "FINAL VALUE",
--0 "UNLIM FLAG",
--0 "NA",
--'NON' "MIN MAX CODE"
--FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
--AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
--INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
--AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
--INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
--WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
--AND ((SELECT ernd_retro_prem_min_max_cd FROM prem_adj_perd 
--WHERE prem_adj_id = PREM_ADJ_RETRO_DTL.prem_adj_id and
--prem_adj_perd_id = PREM_ADJ_RETRO_DTL.prem_adj_perd_id and 
--prem_adj_pgm_id = PREM_ADJ_RETRO_DTL.prem_adj_pgm_id and 
--custmr_id = PREM_ADJ_RETRO_DTL.custmr_id) = 'Min' OR 
--(SELECT ernd_retro_prem_min_max_cd FROM prem_adj_perd 
--WHERE prem_adj_id = PREM_ADJ_RETRO_DTL.prem_adj_id and
--prem_adj_perd_id = PREM_ADJ_RETRO_DTL.prem_adj_perd_id and 
--prem_adj_pgm_id = PREM_ADJ_RETRO_DTL.prem_adj_pgm_id and 
--custmr_id = PREM_ADJ_RETRO_DTL.custmr_id) = 'Max')
--GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--UNION ALL 
---- 36 ERP
--SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
--PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
--'Additional Credits and Charges' "GRP NAME",
--'36' "NUMERICVALUE",
--'Cash Flow Benefit' "DESCRIPTION",
----case when dbo.fn_CheckAdjCFB(PREM_ADJ_RETRO_DTL.PREM_ADJ_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,
----PREM_ADJ_RETRO_DTL.PREM_ADJ_PERD_ID) = 1 then (SUM(PREM_ADJ_RETRO_DTL.ADJ_CASH_FLW_BEN_AMT)) else 
-----(SUM(PREM_ADJ_RETRO_DTL.CASH_FLW_BEN_AMT)) END "FINAL VALUE",
---(SUM(PREM_ADJ_RETRO_DTL.CASH_FLW_BEN_AMT)) "FINAL VALUE",
--0 "UNLIM FLAG",
--0 "NA",
--'NON' "MIN MAX CODE"
--FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
--AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
--INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
--AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
--INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
--WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
--AND ((SELECT ernd_retro_prem_min_max_cd FROM prem_adj_perd 
--WHERE prem_adj_id = PREM_ADJ_RETRO_DTL.prem_adj_id and
--prem_adj_perd_id = PREM_ADJ_RETRO_DTL.prem_adj_perd_id and 
--prem_adj_pgm_id = PREM_ADJ_RETRO_DTL.prem_adj_pgm_id and 
--custmr_id = PREM_ADJ_RETRO_DTL.custmr_id) = 'ERP')
--GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_PERD_ID
--UNION ALL 
-- 36 Min, Max and ERP
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Additional Credits and Charges' "GRP NAME",
'36' "NUMERICVALUE",
'Cash Flow Benefit' "DESCRIPTION",
case when dbo.fn_CheckAdjCFB(PREM_ADJ_RETRO_DTL.PREM_ADJ_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,
PREM_ADJ_RETRO_DTL.PREM_ADJ_PERD_ID) = 1 then (SUM(PREM_ADJ_RETRO_DTL.ADJ_CASH_FLW_BEN_AMT)) else 
-(SUM(PREM_ADJ_RETRO_DTL.CASH_FLW_BEN_AMT)) END "FINAL VALUE",
---(SUM(PREM_ADJ_RETRO_DTL.CASH_FLW_BEN_AMT)) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
--AND ((SELECT ernd_retro_prem_min_max_cd FROM prem_adj_perd 
--WHERE prem_adj_id = PREM_ADJ_RETRO_DTL.prem_adj_id and
--prem_adj_perd_id = PREM_ADJ_RETRO_DTL.prem_adj_perd_id and 
--prem_adj_pgm_id = PREM_ADJ_RETRO_DTL.prem_adj_pgm_id and 
--custmr_id = PREM_ADJ_RETRO_DTL.custmr_id) = 'ERP')
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_PERD_ID
UNION ALL
--37
SELECT PREM_ADJ_RETRO_DTL.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Additional Credits and Charges' "GRP NAME",
'37' "NUMERICVALUE",
'Prior Cash Flow Benefit' "DESCRIPTION",
SUM(PREM_ADJ_RETRO_DTL.PRIOR_CASH_FLW_BEN_AMT) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO_DTL 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO_DTL.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO_DTL.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO_DTL.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO_DTL.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO_DTL.PREM_ADJ_ID
UNION ALL 
--38 LIM PREM AMT
--SELECT PREM_ADJ_MISC_INVC.PREM_ADJ_ID "PREM ADJ ID",
--PREM_ADJ_PERD.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
--'Additional Credits and Charges' "GRP NAME",
--'38' "NUMERICVALUE",
--POST_TRNS_TYP.TRNS_NM_TXT "DESCRIPTION",
--PREM_ADJ_MISC_INVC.POST_AMT "FINAL VALUE",
--0 "UNLIM FLAG",
--'NON' "MIN MAX CODE"
--FROM POST_TRNS_TYP INNER JOIN PREM_ADJ_MISC_INVC ON
--POST_TRNS_TYP.POST_TRNS_TYP_ID = PREM_ADJ_MISC_INVC.POST_TRNS_TYP_ID
--INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_PERD_ID = 
--PREM_ADJ_MISC_INVC.PREM_ADJ_PERD_ID
--WHERE POST_TRNS_TYP.TRNS_TYP_ID = 444 
-- AND PREM_ADJ_MISC_INVC.PREM_ADJ_ID = @ADJNO
-- AND POST_TRNS_TYP.adj_sumry_ind = 1
-- AND POST_TRNS_TYP.ACTV_IND = 1 
-- AND POST_TRNS_TYP.POST_TRNS_TYP_ID = 9 AND dbo.fn_GetCheckforRetro(PREM_ADJ_MISC_INVC.PREM_ADJ_ID,PREM_ADJ_PERD.PREM_ADJ_PGM_ID) = 1
--UNION ALL
----39 PRIOR LIM PREM AMT
--SELECT PREM_ADJ_MISC_INVC.PREM_ADJ_ID "PREM ADJ ID",
--PREM_ADJ_PERD.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
--'Additional Credits and Charges' "GRP NAME",
--'39' "NUMERICVALUE",
--POST_TRNS_TYP.TRNS_NM_TXT "DESCRIPTION",
---(PREM_ADJ_MISC_INVC.POST_AMT) "FINAL VALUE",
--0 "UNLIM FLAG",
--'NON' "MIN MAX CODE"
--FROM POST_TRNS_TYP INNER JOIN PREM_ADJ_MISC_INVC ON
--POST_TRNS_TYP.POST_TRNS_TYP_ID = PREM_ADJ_MISC_INVC.POST_TRNS_TYP_ID
--INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_PERD_ID = 
--PREM_ADJ_MISC_INVC.PREM_ADJ_PERD_ID
--WHERE POST_TRNS_TYP.TRNS_TYP_ID = 444 
-- AND PREM_ADJ_MISC_INVC.PREM_ADJ_ID = @ADJNO
-- AND POST_TRNS_TYP.adj_sumry_ind = 1
-- AND POST_TRNS_TYP.ACTV_IND = 1 
-- AND POST_TRNS_TYP.POST_TRNS_TYP_ID = 10 AND dbo.fn_GetCheckforRetro(PREM_ADJ_MISC_INVC.PREM_ADJ_ID,PREM_ADJ_PERD.PREM_ADJ_PGM_ID) = 1
--UNION ALL
--40 Misc. Invoicing
SELECT DISTINCT PREM_ADJ_MISC_INVC.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_PERD.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Additional Credits and Charges' "GRP NAME",
'40' "NUMERICVALUE",
POST_TRNS_TYP.TRNS_NM_TXT "DESCRIPTION",
PREM_ADJ_MISC_INVC.POST_AMT "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM POST_TRNS_TYP INNER JOIN PREM_ADJ_MISC_INVC ON
POST_TRNS_TYP.POST_TRNS_TYP_ID = PREM_ADJ_MISC_INVC.POST_TRNS_TYP_ID
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_PERD_ID = 
PREM_ADJ_MISC_INVC.PREM_ADJ_PERD_ID
inner join dbo.COML_AGMT on (COML_AGMT.pol_sym_txt = PREM_ADJ_MISC_INVC.pol_sym_txt) 
and (COML_AGMT.pol_nbr_txt = PREM_ADJ_MISC_INVC.pol_nbr_txt) 
and (COML_AGMT.pol_modulus_txt = PREM_ADJ_MISC_INVC.pol_modulus_txt) 
and coml_agmt.actv_ind = 1
WHERE POST_TRNS_TYP.TRNS_TYP_ID = 444 
 AND PREM_ADJ_MISC_INVC.PREM_ADJ_ID = @ADJNO
 AND POST_TRNS_TYP.adj_sumry_ind = 1
 AND POST_TRNS_TYP.ACTV_IND = 1 
 AND POST_TRNS_TYP.pol_reqr_ind = 1
 AND PREM_ADJ_MISC_INVC.ACTV_IND = 1 
 AND POST_TRNS_TYP.POST_TRNS_TYP_ID NOT IN(3,4,11,12,13,9,10)
UNION ALL
--41 Total, 36 to 40
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Additional Credits and Charges' "GRP NAME",
'41' "NUMERICVALUE",
'Total Additional Credits and Charges' "DESCRIPTION",
0 "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID
UNION ALL
--42 Total,35+41
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Additional Credits and Charges' "GRP NAME",
'42' "NUMERICVALUE",
'Sum of Retrospective Premium Adjustment' "DESCRIPTION",
0 "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
NULL "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID
UNION ALL
--43
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Additional Credits and Charges' "GRP NAME",
'43' "NUMERICVALUE",
'Audited Non-Subject Premium' "DESCRIPTION",
SUM(PREM_ADJ_RETRO.NON_SUBJ_AUDT_PREM_AMT) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID
UNION ALL
--44
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Additional Credits and Charges' "GRP NAME",
'44' "NUMERICVALUE",
'Deposit Non-Subject Premium' "DESCRIPTION",
-(SUM(PREM_ADJ_RETRO.NON_SUBJ_DEPST_PREM_AMT)) "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN COML_AGMT ON COML_AGMT.COML_AGMT_ID = PREM_ADJ_RETRO.COML_AGMT_ID AND COML_AGMT.ACTV_IND = 1
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID
UNION ALL
--45 Total 42,43,44
SELECT PREM_ADJ_RETRO.PREM_ADJ_ID "PREM ADJ ID",
PREM_ADJ_RETRO.PREM_ADJ_PGM_ID "PREM ADJ PGM ID",
'Additional Credits and Charges' "GRP NAME",
'45' "NUMERICVALUE",
'Sum of Retrospective Premium Adjustment and Non-Subject Premium' "DESCRIPTION",
0 "FINAL VALUE",
0 "UNLIM FLAG",
0 "NA",
'NON' "MIN MAX CODE"
FROM PREM_ADJ_RETRO 
--INNER JOIN PREM_ADJ_PERD 
--ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ_RETRO.PREM_ADJ_ID
--AND PREM_ADJ_PERD.CUSTMR_ID = PREM_ADJ_RETRO.CUSTMR_ID 
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1 
AND PREM_ADJ_RETRO.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1
WHERE PREM_ADJ_RETRO.PREM_ADJ_ID =  @ADJNO 
GROUP BY PREM_ADJ_RETRO.PREM_ADJ_PGM_ID,PREM_ADJ_RETRO.PREM_ADJ_ID

update #tmpRetro
set "FINAL VALUE" = tm.Summ
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('23','24','25','26','27','28','29')
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" = '30' 

--update #tmpRetro
--set "FINAL VALUE" = r."FINAL VALUE"+tm.Summ
--from #tmpRetro as r
--join 
--(
--SELECT "PREM ADJ PGM ID",case when [dbo].[fn_GetERPAmount](#tmpRetro."PREM ADJ PGM ID",@ADJNO) = 0 then 0 else 
--SUM(#tmpRetro."FINAL VALUE")-[dbo].[fn_GetERPAmount](#tmpRetro."PREM ADJ PGM ID",@ADJNO) end AS Summ
--FROM #tmpRetro WHERE (#tmpRetro."NUMERICVALUE" IN ('12') and #tmpRetro."FINAL VALUE" IS NOT NULL) OR 
--(#tmpRetro."NUMERICVALUE" IN ('13') and #tmpRetro."FINAL VALUE" IS NOT NULL)
--GROUP BY #tmpRetro."PREM ADJ PGM ID"
--) as tm
--on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
--WHERE r."NUMERICVALUE" = '11' and r."FINAL VALUE" IS NOT NULL
--
--update #tmpRetro
--set "FINAL VALUE" = tm.Summ
--from #tmpRetro as r
--join 
--(
--SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
--FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('1','2','3','4','5','6','7','8','9','10','11')
--GROUP BY #tmpRetro."PREM ADJ PGM ID"
--) as tm
--on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
--WHERE r."NUMERICVALUE" = '12' and r."FINAL VALUE" IS NOT NULL
--
--update #tmpRetro
--set "FINAL VALUE" = tm.Summ
--from #tmpRetro as r
--join 
--(
--SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
--FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('1','2','3','4','5','6','7','8','9','10','11')
--GROUP BY #tmpRetro."PREM ADJ PGM ID"
--) as tm
--on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
--WHERE r."NUMERICVALUE" = '13' and r."FINAL VALUE" IS NOT NULL

--update #tmpRetro
--set "FINAL VALUE" = tm.Summ
--from #tmpRetro as r
--join 
--(
--SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
--FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('1','2','3','4','5','6','7','8','9','10','11')
--GROUP BY #tmpRetro."PREM ADJ PGM ID"
--) as tm
--on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
--WHERE r."NUMERICVALUE" = '22' and r."FINAL VALUE" IS NOT NULL

update #tmpRetro
set "FINAL VALUE" = tm.Summ
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('12','14')
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" = '16' and r."FINAL VALUE" IS NOT NULL

update #tmpRetro
set "FINAL VALUE" = tm.Summ
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('13','14','15')
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" = '17' and r."FINAL VALUE" IS NOT NULL

--update #tmpRetro
--set "FINAL VALUE" = tm.Summ
--from #tmpRetro as r
--join 
--(
--SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
--FROM #tmpRetro 
--WHERE #tmpRetro."NUMERICVALUE" IN ('22') 
--GROUP BY #tmpRetro."PREM ADJ PGM ID"
--) as tm
--on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
--WHERE r."NUMERICVALUE" in ('20','21') and r."MIN MAX CODE" = 'ERP' and r."FINAL VALUE" IS NOT NULL
--
--update #tmpRetro
--set "FINAL VALUE" = tm.Summ
--from #tmpRetro as r
--join 
--(
--SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
--FROM #tmpRetro 
--WHERE #tmpRetro."NUMERICVALUE" IN ('20') 
--GROUP BY #tmpRetro."PREM ADJ PGM ID"
--) as tm
--on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
--WHERE r."NUMERICVALUE" in ('22') and (r."MIN MAX CODE" = 'Min' or r."MIN MAX CODE" = 'Max') and r."FINAL VALUE" IS NOT NULL


update #tmpRetro
set "FINAL VALUE" = tm.Summ
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
FROM #tmpRetro 
WHERE #tmpRetro."NUMERICVALUE" IN ('22','30','34') 
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" = '35'

update #tmpRetro
set "FINAL VALUE" = tm.Summ
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('36','37','38','39','40')
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" = '41'

update #tmpRetro
set "FINAL VALUE" = tm.Summ
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('35','41')
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" = '42'

update #tmpRetro
set "FINAL VALUE" = tm.Summ
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID",SUM(#tmpRetro."FINAL VALUE") AS Summ
FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('42','43','44')
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" = '45'

update #tmpRetro
set "MIN MAX CODE" = tm.cnt
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID",Count(#tmpRetro."FINAL VALUE") AS cnt
FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('31','32','33','34')
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" = '35'

update #tmpRetro
set "MIN MAX CODE" = tm.cnt
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID",Count(#tmpRetro."FINAL VALUE") AS cnt
FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('36','37','38','39','40','41')
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" = '42'


update #tmpRetro
set "MIN MAX CODE" = tm.cnt
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID",Count(#tmpRetro."FINAL VALUE") AS cnt
FROM #tmpRetro WHERE #tmpRetro."NUMERICVALUE" IN ('43','44')
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" = '45'

update #tmpRetro
set "DESCRIPTION" = replace("DESCRIPTION" ,'ERP','EDP')
from #tmpRetro as r
join 
(
SELECT "PREM ADJ PGM ID"
FROM #tmpRetro WHERE #tmpRetro."DESCRIPTION"='Earned Deductible Premium (EDP)' and #tmpRetro."NUMERICVALUE"='13'
GROUP BY #tmpRetro."PREM ADJ PGM ID"
) as tm
on r."PREM ADJ PGM ID"= tm."PREM ADJ PGM ID"
WHERE r."NUMERICVALUE" in('20','21','22')


--declare @sql nvarchar(4000)
--set @sql = 'ALTER TABLE #tmpRetro ALTER COLUMN "FINAL VALUE" TEXT NOT NULL'
--exec(@sql)

delete from #tmpRetro WHERE #tmpRetro."FINAL VALUE" IS NULL AND #tmpRetro."NUMERICVALUE" NOT IN ('20','21','22')

delete from #tmpRetro WHERE #tmpRetro."FINAL VALUE" = 0 AND #tmpRetro."NUMERICVALUE" IN ('15')


select * from #tmpRetro order by "PREM ADJ PGM ID",convert(int,"NUMERICVALUE")
drop table #tmpRetro



END TRY
BEGIN CATCH

 
 SELECT 
    ERROR_NUMBER() AS ERRORNUMBER,
    ERROR_SEVERITY() AS ERRORSEVERITY,
    ERROR_STATE() AS ERRORSTATE,
    ERROR_PROCEDURE() AS ERRORPROCEDURE,
    ERROR_LINE() AS ERRORLINE,
    ERROR_MESSAGE() AS ERRORMESSAGE;


END CATCH
END

GO

IF OBJECT_ID('GetRetroSummary') IS NOT NULL
	PRINT 'CREATED PROCEDURE GetRetroSummary'
ELSE
	PRINT 'FAILED CREATING PROCEDURE GetRetroSummary'
GO

IF OBJECT_ID('GetRetroSummary') IS NOT NULL
	GRANT EXEC ON GetRetroSummary TO PUBLIC
GO










