if exists (select 1 from sysobjects where name = 'GetTexasTaxInternal' and type = 'P')
           drop procedure GetTexasTaxInternal
go
SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER ON
GO

---------------------------------------------------------------------  
-----  
----- PROC NAME: GetTexasTaxInternal  
-----  
----- VERSION: SQL SERVER 2005  
-----  
----- AUTHOR : SUNEEL KUMAR MOGALI  
-----  
----- DESCRIPTION: RETURNS DATA WITH RESPECT TO TEXAS TAX INFORMATIOn  
-----     
----- ON EXIT:   
-----     
-----  
----- MODIFIED:   
-----     
-----   
---------------------------------------------------------------------  
  
CREATE PROCEDURE [dbo].[GetTexasTaxInternal]  
@ADJNO INT,  
@FLAG INT,  
@HISTFLAG BIT,  
@CMTCATGID INT  
--@PERDID INT  
AS  
BEGIN  
  
-- SET NOCOUNT ON added to prevent extra result sets from interfering with SELECT statements.  
SET NOCOUNT ON;  
  
  
BEGIN TRY  
  
SELECT CASE @FLAG WHEN 1 THEN PREM_ADJ.DRFT_INVC_NBR_TXT   
WHEN 2 THEN PREM_ADJ.FNL_INVC_NBR_TXT   
ELSE PREM_ADJ.DRFT_INVC_NBR_TXT END "INVOICE NUMBER",  
PREM_ADJ.FNL_INVC_DT "FINAL DATE",  
CASE @FLAG WHEN 1 THEN CONVERT(NVARCHAR(30), DRFT_INVC_DT,101)  
 WHEN 2 THEN CONVERT(NVARCHAR(30), FNL_INVC_DT,101)  
ELSE  CONVERT(NVARCHAR(30), DRFT_INVC_DT,101) END "INVOICE DATE",  
CONVERT(NVARCHAR(30), PREM_ADJ_PGM.STRT_DT, 101) + '-' + CONVERT(NVARCHAR(30), PREM_ADJ_PGM.PLAN_END_DT,101) "PROGRAM PERIOD",  
CONVERT(NVARCHAR(30), PREM_ADJ.VALN_DT, 101) "VALUATION DATE",  
CUSTMR.FULL_NM "INSURED NAME",  
PREM_ADJ_PGM.BRKR_ID "BROKER ID",  
EXTRNL_ORG.FULL_NAME "BROKER",  
dbo.fn_GetILRFLossType(PREM_ADJ_PGM.PREM_ADJ_PGM_ID)  "ADJUSTMENT TYPE",  
PREM_ADJ_PERD.ADJ_NBR_TXT "ADJUSTMENT NUMBER",  
PREM_ADJ_PGM.PREV_VALN_DT "PREV VAL DATE",  
PREM_ADJ_PGM.NXT_VALN_DT "NEXT VAL DATE",  
--PREM_ADJ_PGM_SETUP.INCUR_BUT_NOT_RPTD_LOS_DEV_FCTR_ID,  
--LKUP.LKUP_TXT "LDF/IBNR",  
PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PREM ADJ PERD ID",  
(CASE WHEN dbo.fn_GetPolicyList(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID,400) IS NULL   
THEN '' ELSE RIGHT(dbo.fn_GetPolicyList(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID,400),   
LEN(dbo.fn_GetPolicyList(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID,400))) END) "POLICIES",  
LOB.LKUP_TXT "LOB",  
ST.ATTR_1_TXT "STATE",  
PREM_ADJ_TAX_DTL.TAX_RT "TAX RATE",  
sum(PREM_ADJ_TAX_DTL.TAX_CMPNT_AMT) "TAX COMPONENT AMT",  
sum(PREM_ADJ_TAX_DTL.TAX_AMT) "TOTAL ADDIT RETURN",  
DESCR.LKUP_TXT "DESCRIPTION",  
TAXCMPNT.LKUP_TXT "TAX COMPONENT",  
PREM_ADJ_CMMNT.CMMNT_TXT "COMMENTS",  
convert(decimal,dbo.fn_GetTexasTaxPrevAmt(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID)) "PREV REQ AMT",  
dbo.fn_GetTaxStateStatus(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID,LOB.LKUP_ID,ST.LKUP_ID) "IND STATE",  
dbo.fn_GetTaxStatus(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID) "IND PERD",  
PREM_ADJ.PREM_ADJ_ID "PREM ADJ ID",  
PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM ADJ PGM ID"  
INTO #TEMPBASE  
FROM PREM_ADJ   
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1   
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ.PREM_ADJ_ID  
AND PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID  
INNER JOIN CUSTMR ON PREM_ADJ_PERD.CUSTMR_ID = CUSTMR.CUSTMR_ID  
INNER JOIN EXTRNL_ORG ON EXTRNL_ORG.EXTRNL_ORG_ID = PREM_ADJ_PGM.BRKR_ID  
--LEFT OUTER JOIN LKUP ON LKUP.LKUP_ID = PREM_ADJ_PGM_SETUP.INCUR_BUT_NOT_RPTD_LOS_DEV_FCTR_ID  
LEFT OUTER JOIN PREM_ADJ_TAX_DTL ON PREM_ADJ_TAX_DTL.PREM_ADJ_ID = PREM_ADJ.PREM_ADJ_ID AND   
PREM_ADJ_TAX_DTL.PREM_ADJ_PERD_ID = PREM_ADJ_PERD.PREM_ADJ_PERD_ID AND   
PREM_ADJ_TAX_DTL.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND  
PREM_ADJ_TAX_DTL.CUSTMR_ID = CUSTMR.CUSTMR_ID  
LEFT OUTER JOIN LKUP LOB ON LOB.LKUP_ID = PREM_ADJ_TAX_DTL.LN_OF_BSN_ID  
LEFT OUTER JOIN LKUP ST ON ST.LKUP_ID = PREM_ADJ_TAX_DTL.ST_ID  
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID  
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1  
LEFT OUTER JOIN LKUP DESCR ON DESCR.ATTR_1_TXT = ST.ATTR_1_TXT AND DESCR.LKUP_TYP_ID =  53  
LEFT OUTER JOIN LKUP DEDTAXCOMP ON DEDTAXCOMP.LKUP_ID = PREM_ADJ_TAX_DTL.DEDTBL_TAX_CMPNT_ID  
LEFT OUTER JOIN LKUP TAXCMPNT ON TAXCMPNT.ATTR_1_TXT = DESCR.LKUP_TXT   
AND substring(TAXCMPNT.LKUP_TXT,1,4) = case when len(DEDTAXCOMP.LKUP_TXT) = 3 then DEDTAXCOMP.LKUP_TXT+' ' else DEDTAXCOMP.LKUP_TXT end  
LEFT OUTER JOIN PREM_ADJ_CMMNT ON PREM_ADJ.prem_adj_id = PREM_ADJ_CMMNT.prem_adj_id  
AND PREM_ADJ_CMMNT.PREM_ADJ_PERD_ID = PREM_ADJ_PERD.PREM_ADJ_PERD_ID   
AND PREM_ADJ_CMMNT.CMMNT_CATG_ID = @CMTCATGID  
 WHERE PREM_ADJ.PREM_ADJ_ID =  @ADJNO  
 AND (PREM_ADJ_TAX_DTL.TAX_AMT IS NOT NULL OR convert(decimal,dbo.fn_GetTexasTaxPrevAmt(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID)) IS NOT NULL)  
group by PREM_ADJ.DRFT_INVC_NBR_TXT,PREM_ADJ.FNL_INVC_NBR_TXT,PREM_ADJ.FNL_INVC_DT,DRFT_INVC_DT,PREM_ADJ_PGM.STRT_DT,PREM_ADJ_PGM.PLAN_END_DT,  
PREM_ADJ.VALN_DT,CUSTMR.FULL_NM,PREM_ADJ_PGM.BRKR_ID,EXTRNL_ORG.FULL_NAME,PREM_ADJ_PERD.ADJ_NBR_TXT,PREM_ADJ_PGM.PREV_VALN_DT,PREM_ADJ_PGM.NXT_VALN_DT,  
PREM_ADJ_PERD.PREM_ADJ_PERD_ID,LOB.LKUP_TXT,ST.ATTR_1_TXT,PREM_ADJ_TAX_DTL.TAX_RT,DESCR.LKUP_TXT,TAXCMPNT.LKUP_TXT,  
PREM_ADJ_CMMNT.CMMNT_TXT,PREM_ADJ.PREM_ADJ_ID,PREM_ADJ_PGM.PREM_ADJ_PGM_ID,LOB.LKUP_ID,ST.LKUP_ID  
   
UNION ALL  
  
SELECT CASE @FLAG WHEN 1 THEN PREM_ADJ.DRFT_INVC_NBR_TXT   
WHEN 2 THEN PREM_ADJ.FNL_INVC_NBR_TXT   
ELSE PREM_ADJ.DRFT_INVC_NBR_TXT END "INVOICE NUMBER",  
PREM_ADJ.FNL_INVC_DT "FINAL DATE",  
CASE @FLAG WHEN 1 THEN CONVERT(NVARCHAR(30), DRFT_INVC_DT,101)  
 WHEN 2 THEN CONVERT(NVARCHAR(30), FNL_INVC_DT,101)  
ELSE  CONVERT(NVARCHAR(30), DRFT_INVC_DT,101) END "INVOICE DATE",  
CONVERT(NVARCHAR(30), PREM_ADJ_PGM.STRT_DT, 101) + '-' + CONVERT(NVARCHAR(30), PREM_ADJ_PGM.PLAN_END_DT,101) "PROGRAM PERIOD",  
CONVERT(NVARCHAR(30), PREM_ADJ.VALN_DT, 101) "VALUATION DATE",  
CUSTMR.FULL_NM "INSURED NAME",  
PREM_ADJ_PGM.BRKR_ID "BROKER ID",  
EXTRNL_ORG.FULL_NAME "BROKER",  
dbo.fn_GetILRFLossType(PREM_ADJ_PGM.PREM_ADJ_PGM_ID)  "ADJUSTMENT TYPE",  
PREM_ADJ_PERD.ADJ_NBR_TXT "ADJUSTMENT NUMBER",  
PREM_ADJ_PGM.PREV_VALN_DT "PREV VAL DATE",  
PREM_ADJ_PGM.NXT_VALN_DT "NEXT VAL DATE",  
--PREM_ADJ_PGM_SETUP.INCUR_BUT_NOT_RPTD_LOS_DEV_FCTR_ID,  
--LKUP.LKUP_TXT "LDF/IBNR",  
PREM_ADJ_PERD.PREM_ADJ_PERD_ID "PREM ADJ PERD ID",  
(CASE WHEN dbo.fn_GetPolicyList(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID,400) IS NULL   
THEN '' ELSE RIGHT(dbo.fn_GetPolicyList(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID,400),   
LEN(dbo.fn_GetPolicyList(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID,400))) END) "POLICIES",  
LOB.LKUP_TXT "LOB",  
ST.ATTR_1_TXT "STATE",  
NULL "TAX RATE",  
NULL "TAX COMPONENT AMT",  
PREM_ADJ_TAX_SETUP.ST_SLS_SERV_FEE_TAX "TOTAL ADDIT RETURN",  
DESCR.LKUP_TXT "DESCRIPTION",  
TAXCMPNT.LKUP_TXT "TAX COMPONENT",  
PREM_ADJ_CMMNT.CMMNT_TXT "COMMENTS",  
convert(decimal,dbo.fn_GetTexasTaxPrevAmt(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID)) "PREV REQ AMT",  
'-1' "IND STATE",  
'-1' "IND PERD",  
PREM_ADJ.PREM_ADJ_ID "PREM ADJ ID",  
PREM_ADJ_PGM.PREM_ADJ_PGM_ID "PREM ADJ PGM ID"  
FROM PREM_ADJ   
INNER JOIN PREM_ADJ_PGM ON PREM_ADJ_PGM.ACTV_IND = 1   
INNER JOIN PREM_ADJ_PERD ON PREM_ADJ_PERD.PREM_ADJ_ID = PREM_ADJ.PREM_ADJ_ID  
AND PREM_ADJ_PERD.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID  
INNER JOIN CUSTMR ON PREM_ADJ_PERD.CUSTMR_ID = CUSTMR.CUSTMR_ID  
INNER JOIN EXTRNL_ORG ON EXTRNL_ORG.EXTRNL_ORG_ID = PREM_ADJ_PGM.BRKR_ID  
--LEFT OUTER JOIN LKUP ON LKUP.LKUP_ID = PREM_ADJ_PGM_SETUP.INCUR_BUT_NOT_RPTD_LOS_DEV_FCTR_ID  
LEFT OUTER JOIN PREM_ADJ_TAX_SETUP ON   
PREM_ADJ_TAX_SETUP.PREM_ADJ_ID = PREM_ADJ.PREM_ADJ_ID AND   
PREM_ADJ_TAX_SETUP.PREM_ADJ_PERD_ID = PREM_ADJ_PERD.PREM_ADJ_PERD_ID AND   
PREM_ADJ_TAX_SETUP.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID AND  
PREM_ADJ_TAX_SETUP.CUSTMR_ID = CUSTMR.CUSTMR_ID  
LEFT OUTER JOIN LKUP LOB ON LOB.LKUP_ID = PREM_ADJ_TAX_SETUP.LN_OF_BSN_ID  
LEFT OUTER JOIN LKUP ST ON ST.LKUP_ID = PREM_ADJ_TAX_SETUP.ST_ID  
INNER JOIN PREM_ADJ_PGM_STS ON PREM_ADJ_PGM_STS.PREM_ADJ_PGM_ID = PREM_ADJ_PGM.PREM_ADJ_PGM_ID  
AND PREM_ADJ_PGM_STS.PGM_PERD_STS_TYP_ID = 342 AND PREM_ADJ_PGM_STS.STS_CHK_IND = 1  
LEFT OUTER JOIN LKUP DESCR ON DESCR.ATTR_1_TXT = ST.ATTR_1_TXT AND DESCR.LKUP_TYP_ID =  53  
LEFT OUTER JOIN LKUP TAXCMPNT ON RTRIM(TAXCMPNT.ATTR_1_TXT) = RTRIM(DESCR.LKUP_TXT) AND TAXCMPNT.LKUP_TYP_ID =  55  
LEFT OUTER JOIN PREM_ADJ_CMMNT ON PREM_ADJ.prem_adj_id = PREM_ADJ_CMMNT.prem_adj_id  
AND PREM_ADJ_CMMNT.PREM_ADJ_PERD_ID = PREM_ADJ_PERD.PREM_ADJ_PERD_ID   
AND PREM_ADJ_CMMNT.CMMNT_CATG_ID = @CMTCATGID  
 WHERE PREM_ADJ.PREM_ADJ_ID =  @ADJNO AND PREM_ADJ_TAX_SETUP.ST_SLS_SERV_FEE_TAX IS NOT NULL  
 AND (PREM_ADJ_TAX_SETUP.ST_SLS_SERV_FEE_TAX IS NOT NULL OR convert(decimal,dbo.fn_GetTexasTaxPrevAmt(@ADJNO,PREM_ADJ_PERD.PREM_ADJ_PERD_ID)) IS NOT NULL)  
ORDER BY CONVERT(NVARCHAR(30), PREM_ADJ_PGM.STRT_DT, 101) + '-' + CONVERT(NVARCHAR(30), PREM_ADJ_PGM.PLAN_END_DT,101) DESC  
  
  
SELECT @ADJNO "PREM ADJ ID",  
prem_adj_perd.prem_adj_pgm_id "PREM ADJ PGM ID",  
DESCR.LKUP_TXT+'/'+LOB.LKUP_TXT+'/'+CMPNT.LKUP_TXT "TAX TYPE",  
PREM_ADJ_LOS_REIM_FUND_POST_TAX.CURR_AMT "CURRENT AMT",  
PREM_ADJ_LOS_REIM_FUND_POST_TAX.prior_yy_amt "PRIOR AMT",  
PREM_ADJ_LOS_REIM_FUND_POST_TAX.adj_prior_yy_amt "ADJ PRIOR AMT",  
PREM_ADJ_LOS_REIM_FUND_POST_TAX.post_amt "POST AMT",  
DESCR.LKUP_TXT "DESCR",  
LOB.LKUP_TXT "LOB",  
CMPNT.LKUP_TXT "TAX COMPONENT"  
INTO #TEMPLRFTAX  
FROM PREM_ADJ_LOS_REIM_FUND_POST_TAX INNER JOIN LKUP LOB ON LOB.LKUP_ID  =   
PREM_ADJ_LOS_REIM_FUND_POST_TAX.LN_OF_BSN_ID  
INNER JOIN LKUP ST ON ST.LKUP_ID = PREM_ADJ_LOS_REIM_FUND_POST_TAX.ST_ID  
LEFT OUTER JOIN LKUP DESCR ON DESCR.ATTR_1_TXT = ST.ATTR_1_TXT AND DESCR.LKUP_TYP_ID =  53  
LEFT OUTER JOIN LKUP CMPNT ON CMPNT.lkup_id = PREM_ADJ_LOS_REIM_FUND_POST_TAX.dedtbl_tax_cmpnt_id AND CMPNT.LKUP_TYP_ID =  54  
inner join prem_adj_perd on prem_adj_perd.prem_adj_perd_id = PREM_ADJ_LOS_REIM_FUND_POST_TAX.prem_adj_perd_id  
where PREM_ADJ_LOS_REIM_FUND_POST_TAX.TAX_TYP_ID IS NOT NULL   
AND PREM_ADJ_LOS_REIM_FUND_POST_TAX.PREM_ADJ_ID = @ADJNO   
--AND PREM_ADJ_LOS_REIM_FUND_POST_TAX.PREM_ADJ_PERD_ID = @PERDID  
UNION ALL  
SELECT @ADJNO "PREM ADJ ID",prem_adj_perd.prem_adj_pgm_id "PREM ADJ PGM ID",  
DESCR.LKUP_TXT+'/'+LOB.LKUP_TXT+'/'+'ALAE' "TAX TYPE",  
PREM_ADJ_LOS_REIM_FUND_POST_TAX.CURR_AMT "CURRENT AMT",  
PREM_ADJ_LOS_REIM_FUND_POST_TAX.prior_yy_amt "PRIOR AMT",  
PREM_ADJ_LOS_REIM_FUND_POST_TAX.adj_prior_yy_amt "ADJ PRIOR AMT",  
PREM_ADJ_LOS_REIM_FUND_POST_TAX.post_amt "POST AMT",  
DESCR.LKUP_TXT "DESCR",  
LOB.LKUP_TXT "LOB",  
CMPNT.LKUP_TXT "TAX COMPONENT"  
FROM PREM_ADJ_LOS_REIM_FUND_POST_TAX INNER JOIN LKUP LOB ON LOB.LKUP_ID  =   
PREM_ADJ_LOS_REIM_FUND_POST_TAX.LN_OF_BSN_ID  
INNER JOIN LKUP ST ON ST.LKUP_ID = PREM_ADJ_LOS_REIM_FUND_POST_TAX.ST_ID  
LEFT OUTER JOIN LKUP DESCR ON DESCR.ATTR_1_TXT = ST.ATTR_1_TXT AND DESCR.LKUP_TYP_ID =  53  
LEFT OUTER JOIN LKUP CMPNT ON CMPNT.lkup_id = PREM_ADJ_LOS_REIM_FUND_POST_TAX.dedtbl_tax_cmpnt_id AND CMPNT.LKUP_TYP_ID =  54  
inner join prem_adj_perd on prem_adj_perd.prem_adj_perd_id = PREM_ADJ_LOS_REIM_FUND_POST_TAX.prem_adj_perd_id  
where PREM_ADJ_LOS_REIM_FUND_POST_TAX.TAX_TYP_ID IS NULL  
AND PREM_ADJ_LOS_REIM_FUND_POST_TAX.PREM_ADJ_ID = @ADJNO   
--AND PREM_ADJ_LOS_REIM_FUND_POST_TAX.PREM_ADJ_PERD_ID = @PERDID  
ORDER BY prem_adj_perd.prem_adj_pgm_id DESC,DESCR.LKUP_TXT asc,LOB.LKUP_TXT asc,"TAX TYPE" desc  
  
select * INTO #TEMPBASE1 from #TEMPBASE  
  
  
select distinct #TEMPLRFTAX."PREM ADJ ID",#TEMPLRFTAX."PREM ADJ PGM ID"  
,CONVERT(NVARCHAR(30), PREM_ADJ_PGM.STRT_DT, 101) + '-' + CONVERT(NVARCHAR(30), PREM_ADJ_PGM.PLAN_END_DT,101) "PROGRAM PERIOD"  
,#TEMPBASE1."VALUATION DATE",  
#TEMPBASE1."INSURED NAME",  
#TEMPBASE1."BROKER",  
#TEMPBASE1."ADJUSTMENT TYPE",  
#TEMPBASE1."ADJUSTMENT NUMBER",  
#TEMPBASE1."POLICIES",  
#TEMPLRFTAX."TAX TYPE",  
#TEMPLRFTAX."CURRENT AMT",  
#TEMPLRFTAX."PRIOR AMT",  
#TEMPLRFTAX."ADJ PRIOR AMT",  
#TEMPLRFTAX."POST AMT",  
#TEMPLRFTAX."DESCR",  
#TEMPLRFTAX."LOB",  
#TEMPLRFTAX."TAX COMPONENT"  
from #TEMPBASE1 LEFT OUTER JOIN #TEMPLRFTAX ON #TEMPBASE1."PREM ADJ ID" = #TEMPLRFTAX."PREM ADJ ID" AND #TEMPBASE1."PREM ADJ PGM ID" = #TEMPLRFTAX."PREM ADJ PGM ID"  
INNER JOIN PREM_ADJ_PGM ON #TEMPLRFTAX."PREM ADJ PGM ID" = PREM_ADJ_PGM.PREM_ADJ_PGM_ID  
ORDER BY CONVERT(NVARCHAR(30), PREM_ADJ_PGM.STRT_DT, 101) + '-' + CONVERT(NVARCHAR(30), PREM_ADJ_PGM.PLAN_END_DT,101) DESC,  
#TEMPLRFTAX."DESCR" asc,  
#TEMPLRFTAX."LOB" asc,  
#TEMPLRFTAX."TAX TYPE" asc  
  
drop table #TEMPBASE  
drop table #TEMPBASE1  
drop table #TEMPLRFTAX  
  
  
END TRY  
BEGIN CATCH  
  
 SELECT   
    ERROR_NUMBER() AS ERRORNUMBER,  
    ERROR_SEVERITY() AS ERRORSEVERITY,  
    ERROR_STATE() AS ERRORSTATE,  
    ERROR_PROCEDURE() AS ERRORPROCEDURE,  
    ERROR_LINE() AS ERRORLINE,  
    ERROR_MESSAGE() AS ERRORMESSAGE;  
  
END CATCH  
END 
GO
if object_id('GetTexasTaxInternal') is not null
        print 'Created Procedure GetTexasTaxInternal'
else
        print 'Failed Creating Procedure GetTexasTaxInternal'
go

if object_id('GetTexasTaxInternal') is not null
        grant exec on GetTexasTaxInternal to  public
go

