
truncate table APLCTN_WEB_PAGE_AUTH
go

DBCC CHECKIDENT('APLCTN_WEB_PAGE_AUTH',RESEED,1)

go

--                                                     Inquiry Only (354)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,1,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,2,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,3,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,4,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,5,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,6,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,7,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,8,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,9,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,10,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,11,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,12,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,13,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,14,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,15,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,16,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,17,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,18,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,19,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,20,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,21,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,22,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,23,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,24,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,25,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,26,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,27,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,28,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,29,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,30,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,31,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,32,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,33,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,34,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,35,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,36,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,37,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,38,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,39,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,40,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',354,41,1,'I',1)

--                                                   Setup & Recon (355)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,1,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,2,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,3,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,4,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,5,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,6,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,7,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,8,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,9,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,10,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,11,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,12,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,13,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,14,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,15,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,16,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,17,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,18,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,19,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,20,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,21,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,22,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,23,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,24,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,25,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,26,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,27,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,28,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,29,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,30,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,31,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,32,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,33,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,34,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,35,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,36,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,37,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,38,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,39,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,40,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',355,41,1,'I',1)

--                                                            Adjustment Specialist (356)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,1,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,2,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,3,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,4,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,5,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,6,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,7,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,8,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,9,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,10,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,11,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,12,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,13,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,14,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,15,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,16,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,17,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,18,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,19,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,20,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,21,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,22,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,23,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,24,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,25,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,26,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,27,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,28,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,29,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,30,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,31,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,32,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,33,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,34,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,35,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,36,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,37,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,38,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,39,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,40,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',356,41,1,'F',1)

--                                                             Manager (357)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,1,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,2,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,3,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,4,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,5,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,6,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,7,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,8,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,9,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,10,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,11,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,12,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,13,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,14,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,15,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,16,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,17,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,18,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,19,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,20,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,21,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,22,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,23,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,24,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,25,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,26,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,27,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,28,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,29,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,30,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,31,1,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,32,0,'I',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,33,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,34,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,35,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,36,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,37,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,38,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,39,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,40,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',357,41,1,'F',1)

--                                             System Admin  (358)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,1,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,2,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,3,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,4,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,5,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,6,1,'F',1)
-- During System Test all maintenance pages are read-only for all user groups
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,7,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,8,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,9,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,10,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,11,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,12,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,13,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,14,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,15,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,16,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,17,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,18,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,19,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,20,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,21,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,22,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,23,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,24,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,25,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,26,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,27,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,28,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,29,1,'F',1)
-- During System Test all maintenance pages are read-only for all user groups
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,30,1,'F',1)
-- During System Test all maintenance pages are read-only for all user groups
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,31,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,32,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,33,1,'F',1)

INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,34,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,35,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,36,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,37,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,38,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,39,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,40,1,'F',1)
INSERT INTO [APLCTN_WEB_PAGE_AUTH](crte_dt,[secur_gp_id],[aplctn_menu_id],[authd_ind],[inquiry_full_acss_ind_cd],[crte_user_id])values('01/01/2008',358,41,1,'F',1)






go