//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class LossInfo {
    
    /// <summary>
    /// lblLossInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblLossInfo;
    
    /// <summary>
    /// updInternal control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.UpdatePanel updInternal;
    
    /// <summary>
    /// ValSearch control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ValidationSummary ValSearch;
    
    /// <summary>
    /// valCombined control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ValidationSummary valCombined;
    
    /// <summary>
    /// valCombinedElems control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ValidationSummary valCombinedElems;
    
    /// <summary>
    /// AccountInfoHeader1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::App_Shared_MasterUser AccountInfoHeader1;
    
    /// <summary>
    /// lblErrorMessage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblErrorMessage;
    
    /// <summary>
    /// lblStartDate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblStartDate;
    
    /// <summary>
    /// ddlEffDate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
   // protected global::System.Web.UI.WebControls.DropDownList ddlEffDate;


    /// <summary>
    /// ddlProgramPeriod control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList ddlProgramPeriod;
    
    /// <summary>
    /// CompareddlEffDate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CompareValidator CompareddlEffDate;
    
    /// <summary>
    /// chkHideDisLines control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.CheckBox chkHideDisLines;
    
    /// <summary>
    /// btnDisplayLossesByPol control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnDisplayLossesByPol;
    
    /// <summary>
    /// lblEndDate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    //protected global::System.Web.UI.WebControls.Label lblEndDate;
    
    /// <summary>
    /// ddlEndDate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    //protected global::System.Web.UI.WebControls.DropDownList ddlEndDate;
    
    /// <summary>
    /// CompareddlEndDate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    //protected global::System.Web.UI.WebControls.CompareValidator CompareddlEndDate;
    
    /// <summary>
    /// btnSearch control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnSearch;
    
    /// <summary>
    /// btnDisplayLossesByLob control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnDisplayLossesByLob;
    
    /// <summary>
    /// pnlLossInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlLossInfo;
    
    /// <summary>
    /// objDataSourceState control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ObjectDataSource objDataSourceState;
    
    /// <summary>
    /// objDataSourceLOB control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ObjectDataSource objDataSourceLOB;
    
    /// <summary>
    /// objDataSourcePolicy control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ObjectDataSource objDataSourcePolicy;
    
    /// <summary>
    /// lsvLossInfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.ListView lsvLossInfo;

    /// <summary>
    /// btnLossinfo control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button btnLossinfo;

    protected global::AjaxControlToolkit.ModalPopupExtender modalLossInfoDetails;

    protected global::System.Web.UI.WebControls.DropDownList ddlValuationDate;

    protected global::System.Web.UI.WebControls.DropDownList ddlAdjNo;

    protected global::System.Web.UI.WebControls.Button btnSelectAll;

    protected global::System.Web.UI.WebControls.Button btnPGMSelectAll;

    //protected global::System.Web.UI.WebControls.DropDownList ddlPgmPrd;

    protected global::System.Web.UI.WebControls.CheckBoxList chkpollist;

    protected global::System.Web.UI.WebControls.CheckBoxList chkPGMList;

    protected global::System.Web.UI.WebControls.DropDownList ddlLossType;

    protected global::System.Web.UI.WebControls.Button btnLossDownload;

    protected global::System.Web.UI.WebControls.FileUpload flUpload;

    protected global::System.Web.UI.WebControls.Button btnValidateLoss;

    protected global::System.Web.UI.WebControls.Button btnUploadLoss;

    protected global::System.Web.UI.WebControls.Button btnPopCancel;

    protected global::System.Web.UI.WebControls.Button btnClose;
    protected global::System.Web.UI.WebControls.Label lblErrorLog;

    protected global::System.Web.UI.WebControls.TextBox txtFutureValDate;
    protected global::System.Web.UI.WebControls.Button btnDirectCopy;

    protected global::System.Web.UI.WebControls.DropDownList ddlValuationDateDC;

    protected global::System.Web.UI.WebControls.DropDownList ddlAdjNoDC;

    protected global::System.Web.UI.WebControls.Panel pnlDirectCopy;

    protected global::System.Web.UI.WebControls.Panel pnlSpreadSheetCopy;

    protected global::System.Web.UI.WebControls.RadioButton rbDirectCopy;

    protected global::System.Web.UI.WebControls.RadioButton rbSpreadSheetCopy;
}
