
truncate table LKUP_TYP
go

DBCC CHECKIDENT('LKUP_TYP', RESEED,1)

go

insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','STATE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','DELIVERY METHOD',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ACCOUNT SETUP QC',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ADJUSTMENT TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ALAE TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','LOSS SOURCE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','LOB COVERAGE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','CHF LOSSTYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','PROGRAM TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','TITLE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','CLAIM STATUS - Not being Used',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','EXPOSURE TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','NON-SUBJECT AUDIT PREMIUM',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','RECEIVABLE TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','MASTER ISSUE CHECKLIST TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','REVISION REASON',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','CONTACT TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','TRACKING ISSUES',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','TRACKING FORMS',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','COMMENT CATEGORY',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','RETRO FORMULA COMPONENTS',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','PAID/INCURRED (LBA ADJUSTMENT TYPE)',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','CHF BASIS',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','RETRO FORMULA COMPONENTS - not used',0,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','VOID REASON',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ADJUSTMENT DOCUMENT',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','INVOICE TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','TRANSACTION TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','BKTCY/BUYOUT',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','PER',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','RETROSPECTIVE ELEMENT TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ADJUSTMENT ISSUES - not being used',0,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','PROGRAM STATUSES',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ADJUSTMENT STATUSES',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ROLES',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','RESPONSIBILITY',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ACCOUNT SETUP CHECKLIST ITEM - not being used',0,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ACCOUNT SETUP ISSUES - not being used',0,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ADJUSTMENT CHECKLIST ITEMS - not being used',0,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','TPA BILLING CYCLE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ACCOUNT SETUP QC - not being used',0,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','CLAIM STATUS',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','PENDING REASON CODES',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ADJUSTMENT QC',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','PRIMARY CONTACT',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ADJUSTMENT PARAMETER TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','LRF FACTOR TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','QUALITY CONTROL TYPE',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ILRF PARAMETER',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','ADJUSTMENT SETUP QC',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','LOB',1,1)
insert into LKUP_TYP (crte_dt,lkup_typ_nm_txt,actv_ind, crte_user_id) values('01/01/2008','AUDITING WEB PAGE',1,1)
go
