//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZurichNA.AIS.DAL.LINQ.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAVDB1320;Initial Catalog=AIS;User ID=Retro_user;Password=Cscrac8ng")]
        public string AISConnectionString5 {
            get {
                return ((string)(this["AISConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.233.124;Initial Catalog=AIS;Persist Security Info=True;User ID" +
            "=Retro_user;Password=Cscrac8ng")]
        public string AISConnectionString {
            get {
                return ((string)(this["AISConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAVDB1320;Initial Catalog=AIS;User ID=AIS_WEB_USER;Password=Cscrac8ng" +
            "")]
        public string AISConnectionString1 {
            get {
                return ((string)(this["AISConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=davdb1320;Initial Catalog=AIS;Integrated Security=True")]
        public string AISConnectionString2 {
            get {
                return ((string)(this["AISConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=davdb1320;Initial Catalog=AIS;User ID=retro_user;Password=Cscrac8ng")]
        public string AISConnectionString3 {
            get {
                return ((string)(this["AISConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=davdb1320;Initial Catalog=AIS;Persist Security Info=True;User ID=retr" +
            "o_user;Password=Cscrac8ng")]
        public string AISConnectionString4 {
            get {
                return ((string)(this["AISConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=davdb1320;Initial Catalog=AIS;Persist Security Info=True;User ID=AIS_" +
            "WEB_USER;Password=Cscrac8ng")]
        public string AISConnectionString6 {
            get {
                return ((string)(this["AISConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAVDB1320;Initial Catalog=AIS;Integrated Security=True")]
        public string AISConnectionString7 {
            get {
                return ((string)(this["AISConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=davdb1320;Initial Catalog=AIS;Persist Security Info=True;User ID=Retr" +
            "o_user;Password=Cscrac8ng")]
        public string AISConnectionString8 {
            get {
                return ((string)(this["AISConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAVDB1320;Initial Catalog=AIS;User ID=AIS_WEB_USER")]
        public string AISConnectionString9 {
            get {
                return ((string)(this["AISConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=davdb1320;Initial Catalog=AIS_UAT;User ID=AIS_WEB_USER;Password=Cscra" +
            "c8ng")]
        public string AIS_UATConnectionString {
            get {
                return ((string)(this["AIS_UATConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=davdb1320;Initial Catalog=AIS_UAT;User ID=AIS_WEB_USER;Password=Cscra" +
            "c8ng")]
        public string AIS_UATConnectionString1 {
            get {
                return ((string)(this["AIS_UATConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAVDB1320;Initial Catalog=AIS_UAT_CONV;Integrated Security=True")]
        public string AIS_UAT_CONVConnectionString {
            get {
                return ((string)(this["AIS_UAT_CONVConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAVDB1320;Initial Catalog=AIS_UAT;Integrated Security=True")]
        public string AIS_UATConnectionString2 {
            get {
                return ((string)(this["AIS_UATConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAVDB1320;Initial Catalog=AIS_UAT;User ID=RETRO_user;Password=Cscrac8" +
            "ng")]
        public string AIS_UATConnectionString3 {
            get {
                return ((string)(this["AIS_UATConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAVDB1320;Initial Catalog=AIS_UAT;User ID=AIS_WEB_USER;Password=Cscra" +
            "c8ng")]
        public string AIS_UATConnectionString4 {
            get {
                return ((string)(this["AIS_UATConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DAVDB1320;Initial Catalog=AIS_UAT_TEST;Integrated Security=True")]
        public string AIS_UAT_TESTConnectionString {
            get {
                return ((string)(this["AIS_UAT_TESTConnectionString"]));
            }
        }
    }
}
