
truncate table POST_TRNS_TYP 
go

DBCC CHECKIDENT('POST_TRNS_TYP', RESEED,1)
go

-- Adding Rows
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'TPA Direct Paid Losses','','','Z01',0,0,1,1,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'TPA Funded Deductible Paid Losses','','','Z01',0,0,1,1,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Credit For Estimated Paid Losses - Retro (TPA)','2000','0110','Z01',0,1,1,1,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Credit For Estimated Paid Losses - Retro (TPA) - Prior','','','Z01',0,0,0,1,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Credit For Estimated Paid Losses - AUTO Deductible (TPA)','6000','0129','Z01',1,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Credit For Estimated Paid Losses - GL Deductible (TPA)','6000','0130','Z01',1,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Credit For Estimated Paid Losses- WC Deductible (TPA)','6000','0131','Z01',1,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Credit For Estimated Paid Losses - deductible (TPA) - Prior','','','Z01',0,0,0,0,0,1,0)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Limited Return Prem Amount (Initial) - Disabled','7000','0112','Z01',1,1,0,0,0,1,0)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Limited Ret Prem Withheld','7250','0112','Z01',0,0,0,0,0,1,0)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Excess loss','','','Z01',0,1,1,1,0,1,0)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Insurance charge','','','Z01',0,1,1,1,0,1,0)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Other special charges','','','Z01',0,1,1,1,0,1,0)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Auto LCF Adjust - C&RM','6000','0123','Z01',1,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'GL LCF Adjust - C&RM','6000','0124','Z01',1,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'WC LCF Adjust - C&RM','6000','0125','Z01',1,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',329,'LBA Adjustment - C&RM','6000','0106','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',454,'Retro. Premium Adjustment','1500','0111','Z01',0,1,1,0,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',455,'LF/Escrow Adjustment-C&RM','7000','0105','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',455,'LF/Escrow Adjustment-C&RM','7250','0105','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',455,'Loss Fund/Escrow','7250','0101','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',457,'KY T&A Retro Adjustment','4500','0122','Z01',0,1,1,0,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',458,'OR T&A Retro Adjustment','4500','0147','Z01',0,1,1,0,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',459,'NY Second Injury Fund Adj','4500','0159','Z01',0,1,1,0,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',454,'Retro Adjustment POD','2000','0104','Z01',0,1,1,0,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',456,'Resid Mkt Chge Retro Adj','1500','0117','Z01',0,1,1,0,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',454,'WC TPD Adjust - C&RM','6000','0122','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',454,'TPD Clm Res. Req.- WC Adj','6000','0126','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328,'Auto TPD Adjust - C&RM','6000','0120','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328,'GL TPD Adjust - C&RM','6000','0121','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328,'WC TPD Adjust - C&RM','6000','0122','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328,'Auto LCF Adjust - C&RM','6000','0123','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328,'GL LCF Adjust - C&RM','6000','0124','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328,'WC LCF Adjust - C&RM','6000','0125','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328,'ILRF Adjustment - C&RM','7000','0107','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328,'Incurred Loss Reimb.Fund','7250','0100','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328, 'ILRF Adjustment - C&RM','7250','0107','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'ZSC Claim Service fee','8000','5400','Z18',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'ZSC LCF','8000','5401','Z18',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'Claim Service Fees','8000','0110','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'ZSC Loss Fund/Escrow','7000','0103','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'ZSC LF/Escrow Funds Received','7250','0103','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'ZSC LF/Escrow Funds Returned','7250','0108','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'Third Pty Ded. Paid - Auto','6000','0100','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'Third Pty Ded. Paid - GLO','6000','0101','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'Third Pty Ded. Paid - WC','6000','0102','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'LCF Auto','6000','0103','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'LCF WC','6000','0105','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'LBA - WC','6000','0108','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'Third Pty Ded. Reserve - Auto','6000','0109','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'Third Pty Ded. Reserve - WC','6000','0110','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'Third Pty Ded. Reserve - GL','6000','0111','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'SIR Indemnity & Exp.','6000','0112','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'Paid Loss Bill','6000','0117','Z01',0,1,0,0,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'ZSC Administration Fee','8000','5402','Z18',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'LCF - GL','6000','0104','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'ILRF C&RM','7000','0104','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'ILRF C&RM Fund','7250','0104','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'Conv NPR Paid Loss Bill','6000','0128','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'ELLT','6000','0119','Z01',0,1,0,0,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'TPD Claim Reserve Recd Auto','6250','0109','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'TPD Claim Reserve Recd-WC','6250','0110','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'TPD Claim Reserve Recd-GL','6250','0111','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'TPD Claim Reserve Adj-Auto','6250','0112','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'TPD Claim Reserve Adj-WC','6250','0113','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'TPD Claim Reserve Adj-GL','6250','0114','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'LF/Escrow Adjustment-C&RM','7000','0105','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'WLF Adjustment-C&RM','7000','0106','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',460,'ILRF Adjustment - C&RM','7000','0107','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328, 'LBA Adjustment - C&RM','6000','0106','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',328, 'Reserves','6000','0106','Z01',0,0,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',454,'Def - Retro Bill Reclass','2000','0108','Z01',0,1,1,0,1,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',454,'TPD Clm Reserve Adj-WC','6250','0113','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',327,'Clm Service Fee Adj-C&RM','8000','0130','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',329,'LBA Deposit','7250','0109','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',329,'LBA LF Adjustment - C&RM','7250','0111','Z01',0,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Limited Return Prem Refund','7250','0113','Z01',1,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Limited Return Prem Amount (Initial)','7000','0112','Z01',1,1,0,0,0,1,1)
INSERT INTO [POST_TRNS_TYP] (crte_dt,[trns_typ_id],[trns_nm_txt],[main_nbr_txt],[sub_nbr_txt],[comp_txt],[invoicbl_ind],[post_ind],[thrd_pty_admin_mnl_ind],[adj_sumry_ind],[pol_reqr_ind],[crte_user_id],[actv_ind])
values('01/01/2008',444,'Limited Ret Prem Withheld','7250','0112','Z01',0,1,0,0,0,1,0)


