
PRINT N'Creating [dbo].[TAX_EXMP_SETUP]'
GO
CREATE TABLE [dbo].[TAX_EXMP_SETUP]
(
[tax_exmp_setup_id] [int] NOT NULL IDENTITY(1, 1),
[prem_adj_pgm_id] [int] NOT NULL,
[custmr_id] [int] NOT NULL,
[st_id] [int] NOT NULL,
[updt_user_id] [int] NULL,
[updt_dt] [datetime] NULL,
[crte_user_id] [int] NOT NULL,
[crte_dt] [datetime] NOT NULL,
[actv_ind] [bit] NULL
)

GO
PRINT N'Creating primary key [PK_TAX_EXMP_SETUP] on [dbo].[TAX_EXMP_SETUP]'
GO
ALTER TABLE [dbo].[TAX_EXMP_SETUP] ADD CONSTRAINT [PK_TAX_EXMP_SETUP] PRIMARY KEY CLUSTERED  ([tax_exmp_setup_id])
GO
PRINT N'Creating [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX]'
GO
CREATE TABLE [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX]
(
[prem_adj_los_reim_fund_post_tax_id] [int] NOT NULL IDENTITY(1, 1),
[prem_adj_perd_id] [int] NOT NULL,
[prem_adj_id] [int] NOT NULL,
[custmr_id] [int] NOT NULL,
[tax_typ_id] [int] NULL,
[ln_of_bsn_id] [int] NULL,
[st_id] [int] NULL,
[post_trns_typ_id] [int] NULL,
[curr_amt] [decimal] (15, 2) NULL,
[aggr_amt] [decimal] (15, 2) NULL,
[lim_amt] [decimal] (15, 2) NULL,
[prior_yy_amt] [decimal] (15, 2) NULL,
[adj_prior_yy_amt] [decimal] (15, 2) NULL,
[post_amt] [decimal] (15, 2) NULL,
[updt_user_id] [int] NULL,
[updt_dt] [datetime] NULL,
[crte_dt] [datetime] NOT NULL CONSTRAINT [DF_PREM_ADJ_LOS_REIM_FUND_POST_TAX_crte_dt] DEFAULT (getdate()),
[crte_user_id] [int] NOT NULL
)

GO
PRINT N'Creating primary key [PK_PREM_ADJ_LOS_REIM_FUND_POST_TAX] on [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX]'
GO
ALTER TABLE [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX] ADD CONSTRAINT [PK_PREM_ADJ_LOS_REIM_FUND_POST_TAX] PRIMARY KEY CLUSTERED  ([prem_adj_los_reim_fund_post_tax_id])
GO
PRINT N'Creating [dbo].[PREM_ADJ_TAX_DTL]'
GO
CREATE TABLE [dbo].[PREM_ADJ_TAX_DTL]
(
[prem_adj_tax_dtl_id] [int] NOT NULL IDENTITY(1, 1),
[prem_adj_tax_setup_id] [int] NOT NULL,
[prem_adj_perd_id] [int] NOT NULL,
[prem_adj_id] [int] NOT NULL,
[custmr_id] [int] NOT NULL,
[st_id] [int] NOT NULL,
[ln_of_bsn_id] [int] NOT NULL,
[prem_adj_pgm_id] [int] NOT NULL,
[coml_agmt_id] [int] NOT NULL,
[dedtbl_tax_cmpnt_id] [int] NOT NULL,
[tax_cmpnt_amt] [decimal] (15, 2) NULL,
[tax_rt] [decimal] (15, 8) NULL,
[tax_amt] [decimal] (15, 2) NULL,
[updt_user_id] [int] NULL,
[updt_dt] [datetime] NULL,
[crte_user_id] [int] NOT NULL,
[crte_dt] [datetime] NOT NULL CONSTRAINT [DF_PREM_ADJ_TAX_DTL_crte_dt] DEFAULT (getdate())
)

GO

PRINT N'Creating primary key [PK_PREM_ADJ_TAX_DTL] on [dbo].[PREM_ADJ_TAX_DTL]'
GO
ALTER TABLE [dbo].[PREM_ADJ_TAX_DTL] ADD CONSTRAINT [PK_PREM_ADJ_TAX_DTL] PRIMARY KEY CLUSTERED  ([prem_adj_tax_dtl_id])
GO
PRINT N'Creating [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP]'
GO
CREATE TABLE [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP]
(
[incur_los_reim_fund_tax_id] [int] NOT NULL IDENTITY(1, 1),
[prem_adj_pgm_id] [int] NOT NULL,
[custmr_id] [int] NOT NULL,
[prem_adj_pgm_setup_id] [int] NOT NULL,
[ln_of_bsn_id] [int] NULL,
[tax_typ_id] [int] NOT NULL,
[tax_amt] [decimal] (15, 2) NULL,
[updt_user_id] [int] NULL,
[updt_dt] [datetime] NULL,
[crte_user_id] [int] NOT NULL,
[crte_dt] [datetime] NOT NULL CONSTRAINT [DF_INCUR_LOS_REIM_FUND_TAX_SETUP_crte_dt] DEFAULT (getdate()),
[actv_ind] [bit] NULL
)

GO

PRINT N'Creating primary key [PK_INCUR_LOS_REIM_FUND_TAX_SETUP] on [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP]'
GO
ALTER TABLE [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP] ADD CONSTRAINT [PK_INCUR_LOS_REIM_FUND_TAX_SETUP] PRIMARY KEY CLUSTERED  ([incur_los_reim_fund_tax_id])
GO
PRINT N'Creating [dbo].[PREM_ADJ_TAX_SETUP]'
GO
CREATE TABLE [dbo].[PREM_ADJ_TAX_SETUP]
(
[prem_adj_tax_setup_id] [int] NOT NULL IDENTITY(1, 1),
[prem_adj_perd_id] [int] NOT NULL,
[prem_adj_id] [int] NOT NULL,
[custmr_id] [int] NOT NULL,
[ln_of_bsn_id] [int] NULL,
[st_id] [int] NOT NULL,
[prem_adj_pgm_id] [int] NOT NULL,
[tax_typ_id] [int] NULL,
[tot_tax_amt_st_lvl] [decimal] (15, 2) NULL,
[st_sls_serv_fee_tax] [decimal] (15, 2) NULL,
[tot_tax_amt] [decimal] (15, 2) NULL,
[updt_user_id] [int] NULL,
[updt_dt] [datetime] NULL,
[crte_user_id] [int] NOT NULL,
[crte_dt] [datetime] NOT NULL CONSTRAINT [DF_PREM_ADJ_TAX_SETUP_crte_dt] DEFAULT (getdate())
)

GO

PRINT N'Creating primary key [PK_PREM_ADJ_TAX_SETUP] on [dbo].[PREM_ADJ_TAX_SETUP]'
GO
ALTER TABLE [dbo].[PREM_ADJ_TAX_SETUP] ADD CONSTRAINT [PK_PREM_ADJ_TAX_SETUP] PRIMARY KEY CLUSTERED  ([prem_adj_tax_setup_id], [prem_adj_perd_id], [prem_adj_id], [custmr_id])
GO
PRINT N'Creating [dbo].[DEDTBL_TAX_SETUP]'
GO
CREATE TABLE [dbo].[DEDTBL_TAX_SETUP]
(
[dedtbl_tax_setup_id] [int] NOT NULL IDENTITY(1, 1),
[ln_of_bsn_id] [int] NOT NULL,
[st_id] [int] NOT NULL,
[tax_typ_id] [int] NOT NULL,
[tax_rt] [decimal] (15, 8) NULL,
[pol_eff_dt] [datetime] NULL,
[dedtbl_tax_cmpnt_id] [int] NULL,
[tax_end_dt] [datetime] NULL,
[main_nbr_txt] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[sub_nbr_txt] [char] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[updt_user_id] [int] NULL,
[updt_dt] [datetime] NULL,
[crte_user_id] [int] NOT NULL,
[crte_dt] [datetime] NOT NULL CONSTRAINT [DF_DEDTBL_TAX_SETUP_crte_dt] DEFAULT (getdate()),
[actv_ind] [bit] NULL
)

GO
PRINT N'Creating primary key [PK_DEDTBL_TAX_SETUP] on [dbo].[DEDTBL_TAX_SETUP]'
GO
ALTER TABLE [dbo].[DEDTBL_TAX_SETUP] ADD CONSTRAINT [PK_DEDTBL_TAX_SETUP] PRIMARY KEY CLUSTERED  ([dedtbl_tax_setup_id])
GO
ALTER TABLE [dbo].[DEDTBL_TAX_SETUP]  ADD  CONSTRAINT [FK_DEDTBL_TAX_SETUP_LKUP] FOREIGN KEY([ln_of_bsn_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO
ALTER TABLE [dbo].[DEDTBL_TAX_SETUP]  ADD  CONSTRAINT [FK_DEDTBL_TAX_SETUP_LKUP1] FOREIGN KEY([st_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO
ALTER TABLE [dbo].[DEDTBL_TAX_SETUP]  WITH CHECK ADD  CONSTRAINT [FK_DEDTBL_TAX_SETUP_LKUP2] FOREIGN KEY([dedtbl_tax_cmpnt_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO

PRINT N'Adding foreign keys to [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP]'
GO
ALTER TABLE [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP] ADD
CONSTRAINT [FK_INCUR_LOS_REIM_FUND_TAX_SETUP_PREM_ADJ_PGM] FOREIGN KEY ([prem_adj_pgm_id], [custmr_id]) REFERENCES [dbo].[PREM_ADJ_PGM] ([prem_adj_pgm_id], [custmr_id]),
CONSTRAINT [FK_INCUR_LOS_REIM_FUND_TAX_SETUP_PREM_ADJ_PGM_SETUP] FOREIGN KEY ([prem_adj_pgm_setup_id], [prem_adj_pgm_id], [custmr_id]) REFERENCES [dbo].[PREM_ADJ_PGM_SETUP] ([prem_adj_pgm_setup_id], [prem_adj_pgm_id], [custmr_id])
GO
ALTER TABLE [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP]  ADD  CONSTRAINT [FK_INCUR_LOS_REIM_FUND_TAX_SETUP_LKUP1] FOREIGN KEY([ln_of_bsn_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO
ALTER TABLE [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP]  ADD  CONSTRAINT [FK_INCUR_LOS_REIM_FUND_TAX_SETUP_LKUP2] FOREIGN KEY(tax_typ_id)
REFERENCES [dbo].[LKUP] ([lkup_id])
GO
PRINT N'Adding foreign keys to [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX]'
GO
ALTER TABLE [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX] ADD
CONSTRAINT [FK_PREM_ADJ_LOS_REIM_FUND_POST_TAX_PREM_ADJ_PERD] FOREIGN KEY ([prem_adj_perd_id], [prem_adj_id], [custmr_id]) REFERENCES [dbo].[PREM_ADJ_PERD] ([prem_adj_perd_id], [prem_adj_id], [custmr_id])
GO
ALTER TABLE [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX]  ADD  CONSTRAINT [FK_PREM_ADJ_LOS_REIM_FUND_POST_TAX_LKUP1] FOREIGN KEY([ln_of_bsn_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO
ALTER TABLE [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX]  ADD  CONSTRAINT [FK_PREM_ADJ_LOS_REIM_FUND_POST_TAX_LKUP2] FOREIGN KEY([st_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO
PRINT N'Adding foreign keys to [dbo].[PREM_ADJ_TAX_DTL]'
GO
ALTER TABLE [dbo].[PREM_ADJ_TAX_DTL] ADD
CONSTRAINT [FK_PREM_ADJ_TAX_DTL_PREM_ADJ_TAX_SETUP] FOREIGN KEY ([prem_adj_tax_setup_id], [prem_adj_perd_id], [prem_adj_id], [custmr_id]) REFERENCES [dbo].[PREM_ADJ_TAX_SETUP] ([prem_adj_tax_setup_id], [prem_adj_perd_id], [prem_adj_id], [custmr_id]),
CONSTRAINT [FK_PREM_ADJ_TAX_DTL_COML_AGMT] FOREIGN KEY ([coml_agmt_id], [prem_adj_pgm_id], [custmr_id]) REFERENCES [dbo].[COML_AGMT] ([coml_agmt_id], [prem_adj_pgm_id], [custmr_id])
GO
ALTER TABLE [dbo].[PREM_ADJ_TAX_DTL]  ADD  CONSTRAINT [FK_PREM_ADJ_TAX_DTL_LKUP1] FOREIGN KEY([ln_of_bsn_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO
ALTER TABLE [dbo].[PREM_ADJ_TAX_DTL]  ADD  CONSTRAINT [FK_PREM_ADJ_TAX_DTL_LKUP2] FOREIGN KEY([st_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO
PRINT N'Adding foreign keys to [dbo].[PREM_ADJ_TAX_SETUP]'
GO
ALTER TABLE [dbo].[PREM_ADJ_TAX_SETUP] ADD
CONSTRAINT [FK_PREM_ADJ_TAX_SETUP_PREM_ADJ_PERD] FOREIGN KEY ([prem_adj_perd_id], [prem_adj_id], [custmr_id]) REFERENCES [dbo].[PREM_ADJ_PERD] ([prem_adj_perd_id], [prem_adj_id], [custmr_id]),
CONSTRAINT [FK_PREM_ADJ_TAX_SETUP_PREM_ADJ_PGM] FOREIGN KEY ([prem_adj_pgm_id], [custmr_id]) REFERENCES [dbo].[PREM_ADJ_PGM] ([prem_adj_pgm_id], [custmr_id])
GO
ALTER TABLE [dbo].[PREM_ADJ_TAX_SETUP]  ADD  CONSTRAINT [FK_PREM_ADJ_TAX_SETUP_LKUP1] FOREIGN KEY([ln_of_bsn_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO
ALTER TABLE [dbo].[PREM_ADJ_TAX_SETUP]  ADD  CONSTRAINT [FK_PREM_ADJ_TAX_SETUP_LKUP2] FOREIGN KEY([st_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO
PRINT N'Adding foreign keys to [dbo].[TAX_EXMP_SETUP]'
GO
ALTER TABLE [dbo].[TAX_EXMP_SETUP] ADD
CONSTRAINT [FK_TAX_EXMP_SETUP_PREM_ADJ_PGM] FOREIGN KEY ([prem_adj_pgm_id], [custmr_id]) REFERENCES [dbo].[PREM_ADJ_PGM] ([prem_adj_pgm_id], [custmr_id])
GO
ALTER TABLE [dbo].[TAX_EXMP_SETUP]  ADD  CONSTRAINT [FK_TAX_EXMP_SETUP_LKUP1] FOREIGN KEY([st_id])
REFERENCES [dbo].[LKUP] ([lkup_id])
GO

PRINT N'Creating indexers'
CREATE NONCLUSTERED INDEX [DEDTBL_TAX_SETUP_NN1] ON [dbo].[DEDTBL_TAX_SETUP] 
		(
			[dedtbl_tax_cmpnt_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [DEDTBL_TAX_SETUP_NN2] ON [dbo].[DEDTBL_TAX_SETUP] 
		(
			[ln_of_bsn_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [DEDTBL_TAX_SETUP_NN3] ON [dbo].[DEDTBL_TAX_SETUP] 
		(
			[st_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		

CREATE NONCLUSTERED INDEX [INCUR_LOS_REIM_FUND_TAX_SETUP_NN1] ON [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP] 
		(
			[custmr_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [INCUR_LOS_REIM_FUND_TAX_SETUP_NN2] ON [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP] 
		(
			[custmr_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [INCUR_LOS_REIM_FUND_TAX_SETUP_NN3] ON [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP] 
		(
			[ln_of_bsn_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [INCUR_LOS_REIM_FUND_TAX_SETUP_NN4] ON [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP] 
		(
			[prem_adj_pgm_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [INCUR_LOS_REIM_FUND_TAX_SETUP_NN5] ON [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP] 
		(
			[prem_adj_pgm_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [INCUR_LOS_REIM_FUND_TAX_SETUP_NN6] ON [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP] 
		(
			[prem_adj_pgm_setup_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [INCUR_LOS_REIM_FUND_TAX_SETUP_NN7] ON [dbo].[INCUR_LOS_REIM_FUND_TAX_SETUP] 
		(
			[tax_typ_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]



		
CREATE NONCLUSTERED INDEX [PREM_ADJ_LOS_REIM_FUND_POST_TAX_NN1] ON [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX] 
		(
			[custmr_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_LOS_REIM_FUND_POST_TAX_NN2] ON [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX] 
		(
			[ln_of_bsn_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_LOS_REIM_FUND_POST_TAX_NN3] ON [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX] 
		(
			[prem_adj_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_LOS_REIM_FUND_POST_TAX_NN4] ON [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX] 
		(
			[prem_adj_perd_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_LOS_REIM_FUND_POST_TAX_NN5] ON [dbo].[PREM_ADJ_LOS_REIM_FUND_POST_TAX] 
		(
			[st_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		




CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_DTL_NN1] ON [dbo].[PREM_ADJ_TAX_DTL] 
		(
			[coml_agmt_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_DTL_NN2] ON [dbo].[PREM_ADJ_TAX_DTL] 
		(
			[custmr_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_DTL_NN3] ON [dbo].[PREM_ADJ_TAX_DTL] 
		(
			[custmr_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_DTL_NN4] ON [dbo].[PREM_ADJ_TAX_DTL] 
		(
			[ln_of_bsn_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_DTL_NN5] ON [dbo].[PREM_ADJ_TAX_DTL] 
		(
			[prem_adj_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_DTL_NN6] ON [dbo].[PREM_ADJ_TAX_DTL] 
		(
			[prem_adj_perd_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_DTL_NN7] ON [dbo].[PREM_ADJ_TAX_DTL] 
		(
			[prem_adj_pgm_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_DTL_NN8] ON [dbo].[PREM_ADJ_TAX_DTL] 
		(
			[prem_adj_tax_setup_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_DTL_NN9] ON [dbo].[PREM_ADJ_TAX_DTL] 
		(
			[st_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]



		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_SETUP_NN1] ON [dbo].[PREM_ADJ_TAX_SETUP] 
		(
			[ln_of_bsn_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_SETUP_NN2] ON [dbo].[PREM_ADJ_TAX_SETUP] 
		(
			[prem_adj_pgm_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [PREM_ADJ_TAX_SETUP_NN3] ON [dbo].[PREM_ADJ_TAX_SETUP] 
		(
			[st_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]



		
CREATE NONCLUSTERED INDEX [TAX_EXMP_SETUP_NN1] ON [dbo].[TAX_EXMP_SETUP] 
		(
			[custmr_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [TAX_EXMP_SETUP_NN2] ON [dbo].[TAX_EXMP_SETUP] 
		(
			[prem_adj_pgm_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
CREATE NONCLUSTERED INDEX [TAX_EXMP_SETUP_NN3] ON [dbo].[TAX_EXMP_SETUP] 
		(
			[st_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
		
GO